'use strict';

function skillTreeGlobalDebuffEffects(stat, amount){
  return Object.keys(CLASSES).map(classId => ({ type:'stat', classId, stat, amount }));
}

const SKILL_TREE_GENERAL_NODES = [

  { id:'gen_loot_hub', parent:'general_hub', cost:1,
    name:'Coin Instinct',
    desc:'Slightly increases the odds of coins from room-clear rewards.',
    effect:{ type:'poolWeight', pool:'COMMON_CATEGORY_POOL', id:'penny', bonus:2 } },
  { id:'gen_loot_coins', parent:'gen_loot_hub', cost:1,
    name:'Sharper Eye for Silver',
    desc:'Slightly increases the odds of a nickel over a plain penny.',
    effect:{ type:'poolWeight', pool:'COMMON_PENNY_POOL', id:'nickel', bonus:2 } },
  { id:'gen_loot_coins2', parent:'gen_loot_coins', cost:1,
    name:'Gilded Instinct',
    desc:'Slightly increases the odds of a dime over a plain penny.',
    effect:{ type:'poolWeight', pool:'COMMON_PENNY_POOL', id:'dime', bonus:1 } },
  { id:'gen_loot_luck', parent:'gen_loot_hub', cost:1,
    name:'Fortunate Find',
    desc:'Slightly increases the odds of a lucky penny over a plain penny.',
    effect:{ type:'poolWeight', pool:'COMMON_PENNY_POOL', id:'luckypenny', bonus:1 } },
  { id:'gen_loot_hearts', parent:'general_hub', cost:1,
    name:'Vital Instinct',
    desc:'Slightly increases the odds of hearts from room-clear rewards.',
    effect:{ type:'poolWeight', pool:'COMMON_CATEGORY_POOL', id:'heart', bonus:2 } },
  { id:'gen_loot_blueheart', parent:'gen_loot_hearts', cost:1,
    name:'Soulbound Affinity',
    desc:'Slightly increases the odds of a blue heart over a red one.',
    effect:{ type:'poolWeight', pool:'COMMON_HEART_POOL', id:'heartBlue', bonus:3 } },
  { id:'gen_loot_doubleheart', parent:'gen_loot_hearts', cost:1,
    name:'Twin Heart Sense',
    desc:'Slightly increases the odds of a double heart from room-clear rewards.',
    effect:{ type:'poolWeight', pool:'COMMON_HEART_POOL', id:'doubleheart', bonus:1 } },

  { id:'gen_supply_hub', parent:'general_hub', cost:1,
    name:"Explosive Instinct",
    desc:'Slightly increases the odds of bombs from room-clear rewards.',
    effect:{ type:'poolWeight', pool:'COMMON_CATEGORY_POOL', id:'bomb', bonus:3 } },
  { id:'gen_supply_doublebomb', parent:'gen_supply_hub', cost:1,
    name:'Twin Fuse',
    desc:'Slightly increases the odds of a double bomb over a plain bomb.',
    effect:{ type:'poolWeight', pool:'BOMB_TIER_POOL', id:'doublebomb', bonus:2 } },
  { id:'gen_supply_goldbomb', parent:'gen_supply_doublebomb', cost:1,
    name:'Golden Fuse',
    desc:'Slightly increases the odds of a golden bomb over a plain bomb.',
    effect:{ type:'poolWeight', pool:'BOMB_TIER_POOL', id:'goldbomb', bonus:1 } },
  { id:'gen_supply_key_hub', parent:'general_hub', cost:1,
    name:"Locksmith's Instinct",
    desc:'Slightly increases the odds of keys from room-clear rewards.',
    effect:{ type:'poolWeight', pool:'COMMON_CATEGORY_POOL', id:'key', bonus:3 } },
  { id:'gen_supply_doublekey', parent:'gen_supply_key_hub', cost:1,
    name:'Twin Ward',
    desc:'Slightly increases the odds of a double key over a plain key.',
    effect:{ type:'poolWeight', pool:'KEY_TIER_POOL', id:'doublekey', bonus:2 } },
  { id:'gen_supply_goldkey', parent:'gen_supply_doublekey', cost:1,
    name:'Golden Ward',
    desc:'Slightly increases the odds of a golden key over a plain key.',
    effect:{ type:'poolWeight', pool:'KEY_TIER_POOL', id:'goldkey', bonus:1 } },

  { id:'gen_start_hub', parent:'general_hub', cost:1,
    name:'Packed Satchel',
    desc:'Start each run with 1 extra bomb.',
    effect:{ type:'startingPickup', pickup:'bombs', amount:1 } },
  { id:'gen_start_keys', parent:'gen_start_hub', cost:1,
    name:'Ready Keyring',
    desc:'Start each run with 1 extra key.',
    effect:{ type:'startingPickup', pickup:'keys', amount:1 } },
  { id:'gen_start_coins', parent:'general_hub', cost:1,
    name:'Spare Change',
    desc:'Start each run with 3 extra coins.',
    effect:{ type:'startingPickup', pickup:'coins', amount:3 } },
  { id:'gen_start_coins2', parent:'gen_start_coins', cost:1,
    name:'Deeper Pockets',
    desc:'Start each run with 2 more extra coins.',
    effect:{ type:'startingPickup', pickup:'coins', amount:2 } },
  { id:'gen_start_blue', parent:'general_hub', cost:1,
    name:'Soul Reserve',
    desc:'Start each run with 1 extra soul (blue) heart.',
    effect:{ type:'startingPickup', pickup:'blue', amount:1 } },

  { id:'gen_rare_gate', parent:'general_hub', cost:1, cursed:true,
    name:'Toll of the Rare Find',
    desc:'Fortune this good is never free. Permanently reduces luck by 2%. Required to reach the Rare & Legendary Fortune branch.',
    effects: skillTreeGlobalDebuffEffects('luck', -0.02) },
  { id:'gen_rare_hub', parent:'gen_rare_gate', cost:1,
    name:'Starlit Favor',
    desc:'Slightly increases the odds of a star from a rare room-clear reward.',
    effect:{ type:'poolWeight', pool:'RARE_POOL', id:'star', bonus:3 } },
  { id:'gen_rare_sack', parent:'gen_rare_hub', cost:1,
    name:'Bountiful Sack',
    desc:'Slightly increases the odds of a sack from a rare room-clear reward.',
    effect:{ type:'poolWeight', pool:'RARE_POOL', id:'sack', bonus:3 } },
  { id:'gen_rare_battery', parent:'gen_rare_hub', cost:1,
    name:'Charged Instinct',
    desc:'Slightly increases the odds of a battery from a rare room-clear reward.',
    effect:{ type:'poolWeight', pool:'RARE_POOL', id:'battery', bonus:3 } },
  { id:'gen_rare_generous', parent:'gen_rare_battery', cost:1,
    name:'Generous Recovery',
    desc:'Slightly increases the odds of both batteries and half blue hearts from room-clear rewards.',
    effects:[
      { type:'poolWeight', pool:'RARE_POOL', id:'battery', bonus:2 },
      { type:'poolWeight', pool:'COMMON_HEART_POOL', id:'halfheartBlue', bonus:2 },
    ] },
  { id:'gen_leg_gate', parent:'general_hub', cost:1, cursed:true,
    name:'Toll of the Legendary Find',
    desc:'The rarest drops demand the steepest toll. Permanently reduces luck by 2%. Required to reach the legendary half of the Fortune branch.',
    effects: skillTreeGlobalDebuffEffects('luck', -0.02) },
  { id:'gen_leg_hub', parent:'gen_leg_gate', cost:1,
    name:'Trinket Sense',
    desc:'Slightly increases the odds of a trinket from a legendary room-clear reward.',
    effect:{ type:'poolWeight', pool:'LEGENDARY_POOL', id:'trinket', bonus:3 } },
  { id:'gen_leg_familiar', parent:'gen_leg_hub', cost:1,
    name:'Companion Call',
    desc:'Slightly increases the odds of a familiar from a legendary room-clear reward.',
    effect:{ type:'poolWeight', pool:'LEGENDARY_POOL', id:'familiar', bonus:1 } },

  { id:'gen_chest_hub', parent:'general_hub', cost:1,
    name:'Cursed Curiosity',
    desc:'Slightly increases the odds of a cursed chest whenever a chest appears.',
    effect:{ type:'poolWeight', pool:'CHEST_TYPE_POOL', id:'cursed', bonus:2 } },

  { id:'gen_global_hub', parent:'general_hub', cost:1,
    name:'Universal Footwork',
    desc:'Slightly increases every character\'s movement speed.',
    effect:{ type:'globalStat', stat:'speed', amount:0.01 } },
  { id:'gen_global_crit', parent:'gen_global_hub', cost:1,
    name:'Shared Precision',
    desc:'Slightly increases every character\'s critical hit chance.',
    effect:{ type:'globalStat', stat:'critChance', amount:0.01 } },
  { id:'gen_global_magnet', parent:'gen_global_hub', cost:1,
    name:'Collective Pull',
    desc:'Slightly increases every character\'s pickup magnet radius.',
    effect:{ type:'globalStat', stat:'magnetRadius', amount:0.01 } },
  { id:'gen_global_melee', parent:'gen_global_crit', cost:2,
    name:'Tempered Resolve',
    desc:'Increases every character\'s melee damage.',
    effect:{ type:'globalStat', stat:'meleeDamage', amount:0.02 } },
  { id:'gen_global_ranged', parent:'gen_global_magnet', cost:2,
    name:'Steadied Aim',
    desc:'Increases every character\'s ranged damage.',
    effect:{ type:'globalStat', stat:'rangedDamage', amount:0.02 } },
  { id:'gen_global_reload', parent:'gen_global_melee', cost:2,
    name:'Shared Rhythm',
    desc:'Slightly reduces every character\'s fire cooldown.',
    effect:{ type:'globalStat', stat:'fireCooldown', amount:-0.02 } },
  { id:'gen_global_gate', parent:'gen_global_reload', cost:2, cursed:true,
    name:'Toll of the Overclocked Mind',
    desc:'Pushing every character past their limits together carries a shared price. Increases every character\'s ranged damage further, but permanently reduces every character\'s luck by 2%.',
    effects:[
      { type:'globalStat', stat:'rangedDamage', amount:0.02 },
      ...skillTreeGlobalDebuffEffects('luck', -0.02),
    ] },
  { id:'gen_global_boltspeed', parent:'gen_global_gate', cost:3,
    name:'Overclocked Volley',
    desc:'Noticeably increases every character\'s projectile speed.',
    effect:{ type:'globalStat', stat:'boltSpeed', amount:0.03 } },
  { id:'gen_global_capstone', parent:'gen_global_boltspeed', cost:3,
    name:'Unified Vigor',
    desc:'Noticeably increases every character\'s movement speed and effective range.',
    effects:[
      { type:'globalStat', stat:'speed', amount:0.02 },
      { type:'globalStat', stat:'rangeTiles', amount:0.02 },
    ] },

  { id:'gen_gm2_meleecooldown_hub', parent:'general_hub', cost:1,
    name:'Brisk Swing',
    desc:'Slightly quickens every character\'s attack rhythm.',
    effect:{ type:'globalStat', stat:'meleeCooldown', amount:-0.01 } },
  { id:'gen_gm2_meleecooldown_c1', parent:'gen_gm2_meleecooldown_hub', cost:1,
    name:'Fluid Follow-Through',
    desc:'Further quickens every character\'s attack rhythm.',
    effect:{ type:'globalStat', stat:'meleeCooldown', amount:-0.01 } },
  { id:'gen_gm2_meleecooldown_c2', parent:'gen_gm2_meleecooldown_c1', cost:1,
    name:'Practiced Combo',
    desc:'Continues to quicken every character\'s attack rhythm.',
    effect:{ type:'globalStat', stat:'meleeCooldown', amount:-0.01 } },
  { id:'gen_gm2_meleecooldown_gate', parent:'gen_gm2_meleecooldown_c2', cost:1, cursed:true,
    name:'Toll of the Brisk Swing',
    desc:'Mastering attack rhythm this deeply carries a price. Permanently reduces every character\'s luck by 1%. Required to reach Relentless Cadence.',
    effects:
    skillTreeGlobalDebuffEffects('luck', -0.01) },
  { id:'gen_gm2_meleecooldown_cap', parent:'gen_gm2_meleecooldown_gate', cost:2,
    name:'Relentless Cadence',
    desc:'Noticeably quickens every character\'s attack rhythm.',
    effect:{ type:'globalStat', stat:'meleeCooldown', amount:-0.02 } },
  { id:'gen_gm2_luck_hub', parent:'general_hub', cost:1,
    name:'Lucky Streak',
    desc:'Slightly increases every character\'s luck.',
    effect:{ type:'globalStat', stat:'luck', amount:0.01 } },
  { id:'gen_gm2_luck_c1', parent:'gen_gm2_luck_hub', cost:1,
    name:'Favorable Odds',
    desc:'Further increases every character\'s luck.',
    effect:{ type:'globalStat', stat:'luck', amount:0.01 } },
  { id:'gen_gm2_luck_c2', parent:'gen_gm2_luck_c1', cost:1,
    name:'Charmed Path',
    desc:'Continues to increase every character\'s luck.',
    effect:{ type:'globalStat', stat:'luck', amount:0.01 } },
  { id:'gen_gm2_luck_gate', parent:'gen_gm2_luck_c2', cost:1, cursed:true,
    name:'Toll of the Lucky Streak',
    desc:'Mastering luck this deeply carries a price. Permanently reduces every character\'s speed by 1%. Required to reach Fortune\'s Smile.',
    effects:
    skillTreeGlobalDebuffEffects('speed', -0.01) },
  { id:'gen_gm2_luck_cap', parent:'gen_gm2_luck_gate', cost:2,
    name:'Fortune\'s Smile',
    desc:'Noticeably increases every character\'s luck.',
    effect:{ type:'globalStat', stat:'luck', amount:0.02 } },
  { id:'gen_gm2_venom_hub', parent:'general_hub', cost:1,
    name:'Toxic Touch',
    desc:'Slightly increases every character\'s chance to poison on hit.',
    effect:{ type:'globalStat', stat:'venomChance', amount:0.01 } },
  { id:'gen_gm2_venom_c1', parent:'gen_gm2_venom_hub', cost:1,
    name:'Bitter Coating',
    desc:'Further increases every character\'s chance to poison on hit.',
    effect:{ type:'globalStat', stat:'venomChance', amount:0.01 } },
  { id:'gen_gm2_venom_c2', parent:'gen_gm2_venom_c1', cost:1,
    name:'Seeping Venom',
    desc:'Continues to increase every character\'s chance to poison on hit.',
    effect:{ type:'globalStat', stat:'venomChance', amount:0.01 } },
  { id:'gen_gm2_venom_gate', parent:'gen_gm2_venom_c2', cost:1, cursed:true,
    name:'Toll of the Toxic Touch',
    desc:'Mastering chance to poison on hit this deeply carries a price. Permanently reduces every character\'s luck by 1%. Required to reach Virulent Strike.',
    effects:
    skillTreeGlobalDebuffEffects('luck', -0.01) },
  { id:'gen_gm2_venom_cap', parent:'gen_gm2_venom_gate', cost:2,
    name:'Virulent Strike',
    desc:'Noticeably increases every character\'s chance to poison on hit.',
    effect:{ type:'globalStat', stat:'venomChance', amount:0.02 } },
  { id:'gen_gm2_stun_hub', parent:'general_hub', cost:1,
    name:'Heavy Impact',
    desc:'Slightly increases every character\'s chance to stun on hit.',
    effect:{ type:'globalStat', stat:'stunChance', amount:0.01 } },
  { id:'gen_gm2_stun_c1', parent:'gen_gm2_stun_hub', cost:1,
    name:'Staggering Blow',
    desc:'Further increases every character\'s chance to stun on hit.',
    effect:{ type:'globalStat', stat:'stunChance', amount:0.01 } },
  { id:'gen_gm2_stun_c2', parent:'gen_gm2_stun_c1', cost:1,
    name:'Rattling Force',
    desc:'Continues to increase every character\'s chance to stun on hit.',
    effect:{ type:'globalStat', stat:'stunChance', amount:0.01 } },
  { id:'gen_gm2_stun_gate', parent:'gen_gm2_stun_c2', cost:1, cursed:true,
    name:'Toll of the Heavy Impact',
    desc:'Mastering chance to stun on hit this deeply carries a price. Permanently reduces every character\'s luck by 1%. Required to reach Concussive Strike.',
    effects:
    skillTreeGlobalDebuffEffects('luck', -0.01) },
  { id:'gen_gm2_stun_cap', parent:'gen_gm2_stun_gate', cost:2,
    name:'Concussive Strike',
    desc:'Noticeably increases every character\'s chance to stun on hit.',
    effect:{ type:'globalStat', stat:'stunChance', amount:0.02 } },
  { id:'gen_gm2_charm_hub', parent:'general_hub', cost:1,
    name:'Beguiling Aura',
    desc:'Slightly increases every character\'s chance to charm on hit.',
    effect:{ type:'globalStat', stat:'charmChance', amount:0.01 } },
  { id:'gen_gm2_charm_c1', parent:'gen_gm2_charm_hub', cost:1,
    name:'Enthralling Gaze',
    desc:'Further increases every character\'s chance to charm on hit.',
    effect:{ type:'globalStat', stat:'charmChance', amount:0.01 } },
  { id:'gen_gm2_charm_c2', parent:'gen_gm2_charm_c1', cost:1,
    name:'Bewitching Touch',
    desc:'Continues to increase every character\'s chance to charm on hit.',
    effect:{ type:'globalStat', stat:'charmChance', amount:0.01 } },
  { id:'gen_gm2_charm_gate', parent:'gen_gm2_charm_c2', cost:1, cursed:true,
    name:'Toll of the Beguiling Aura',
    desc:'Mastering chance to charm on hit this deeply carries a price. Permanently reduces every character\'s luck by 1%. Required to reach Mesmeric Strike.',
    effects:
    skillTreeGlobalDebuffEffects('luck', -0.01) },
  { id:'gen_gm2_charm_cap', parent:'gen_gm2_charm_gate', cost:2,
    name:'Mesmeric Strike',
    desc:'Noticeably increases every character\'s chance to charm on hit.',
    effect:{ type:'globalStat', stat:'charmChance', amount:0.02 } },
  { id:'gen_gm2_freeze_hub', parent:'general_hub', cost:1,
    name:'Chilling Touch',
    desc:'Slightly increases every character\'s chance to freeze on hit.',
    effect:{ type:'globalStat', stat:'freezeChance', amount:0.01 } },
  { id:'gen_gm2_freeze_c1', parent:'gen_gm2_freeze_hub', cost:1,
    name:'Frosted Edge',
    desc:'Further increases every character\'s chance to freeze on hit.',
    effect:{ type:'globalStat', stat:'freezeChance', amount:0.01 } },
  { id:'gen_gm2_freeze_c2', parent:'gen_gm2_freeze_c1', cost:1,
    name:'Numbing Cold',
    desc:'Continues to increase every character\'s chance to freeze on hit.',
    effect:{ type:'globalStat', stat:'freezeChance', amount:0.01 } },
  { id:'gen_gm2_freeze_gate', parent:'gen_gm2_freeze_c2', cost:1, cursed:true,
    name:'Toll of the Chilling Touch',
    desc:'Mastering chance to freeze on hit this deeply carries a price. Permanently reduces every character\'s luck by 1%. Required to reach Absolute Zero Strike.',
    effects:
    skillTreeGlobalDebuffEffects('luck', -0.01) },
  { id:'gen_gm2_freeze_cap', parent:'gen_gm2_freeze_gate', cost:2,
    name:'Absolute Zero Strike',
    desc:'Noticeably increases every character\'s chance to freeze on hit.',
    effect:{ type:'globalStat', stat:'freezeChance', amount:0.02 } },
  { id:'gen_gm2_fear_hub', parent:'general_hub', cost:1,
    name:'Unnerving Presence',
    desc:'Slightly increases every character\'s chance to frighten on hit.',
    effect:{ type:'globalStat', stat:'fearChance', amount:0.01 } },
  { id:'gen_gm2_fear_c1', parent:'gen_gm2_fear_hub', cost:1,
    name:'Cold Stare',
    desc:'Further increases every character\'s chance to frighten on hit.',
    effect:{ type:'globalStat', stat:'fearChance', amount:0.01 } },
  { id:'gen_gm2_fear_c2', parent:'gen_gm2_fear_c1', cost:1,
    name:'Looming Dread',
    desc:'Continues to increase every character\'s chance to frighten on hit.',
    effect:{ type:'globalStat', stat:'fearChance', amount:0.01 } },
  { id:'gen_gm2_fear_gate', parent:'gen_gm2_fear_c2', cost:1, cursed:true,
    name:'Toll of the Unnerving Presence',
    desc:'Mastering chance to frighten on hit this deeply carries a price. Permanently reduces every character\'s luck by 1%. Required to reach Terrifying Strike.',
    effects:
    skillTreeGlobalDebuffEffects('luck', -0.01) },
  { id:'gen_gm2_fear_cap', parent:'gen_gm2_fear_gate', cost:2,
    name:'Terrifying Strike',
    desc:'Noticeably increases every character\'s chance to frighten on hit.',
    effect:{ type:'globalStat', stat:'fearChance', amount:0.02 } },
  { id:'gen_gm2_vulnerable_hub', parent:'general_hub', cost:1,
    name:'Probing Strike',
    desc:'Slightly increases every character\'s chance to expose weaknesses on hit.',
    effect:{ type:'globalStat', stat:'vulnerableChance', amount:0.01 } },
  { id:'gen_gm2_vulnerable_c1', parent:'gen_gm2_vulnerable_hub', cost:1,
    name:'Exploit Opening',
    desc:'Further increases every character\'s chance to expose weaknesses on hit.',
    effect:{ type:'globalStat', stat:'vulnerableChance', amount:0.01 } },
  { id:'gen_gm2_vulnerable_c2', parent:'gen_gm2_vulnerable_c1', cost:1,
    name:'Sundering Blow',
    desc:'Continues to increase every character\'s chance to expose weaknesses on hit.',
    effect:{ type:'globalStat', stat:'vulnerableChance', amount:0.01 } },
  { id:'gen_gm2_vulnerable_gate', parent:'gen_gm2_vulnerable_c2', cost:1, cursed:true,
    name:'Toll of the Probing Strike',
    desc:'Mastering chance to expose weaknesses on hit this deeply carries a price. Permanently reduces every character\'s luck by 1%. Required to reach Ruinous Strike.',
    effects:
    skillTreeGlobalDebuffEffects('luck', -0.01) },
  { id:'gen_gm2_vulnerable_cap', parent:'gen_gm2_vulnerable_gate', cost:2,
    name:'Ruinous Strike',
    desc:'Noticeably increases every character\'s chance to expose weaknesses on hit.',
    effect:{ type:'globalStat', stat:'vulnerableChance', amount:0.02 } },
  { id:'gen_gm2_lifesteal_hub', parent:'general_hub', cost:1,
    name:'Vital Siphon',
    desc:'Slightly increases every character\'s chance to heal on hit.',
    effect:{ type:'globalStat', stat:'lifestealChance', amount:0.005 } },
  { id:'gen_gm2_lifesteal_c1', parent:'gen_gm2_lifesteal_hub', cost:1,
    name:'Hungry Edge',
    desc:'Further increases every character\'s chance to heal on hit.',
    effect:{ type:'globalStat', stat:'lifestealChance', amount:0.005 } },
  { id:'gen_gm2_lifesteal_c2', parent:'gen_gm2_lifesteal_c1', cost:1,
    name:'Draining Touch',
    desc:'Continues to increase every character\'s chance to heal on hit.',
    effect:{ type:'globalStat', stat:'lifestealChance', amount:0.005 } },
  { id:'gen_gm2_lifesteal_gate', parent:'gen_gm2_lifesteal_c2', cost:1, cursed:true,
    name:'Toll of the Vital Siphon',
    desc:'Mastering chance to heal on hit this deeply carries a price. Permanently reduces every character\'s luck by 1%. Required to reach Ravenous Strike.',
    effects:
    skillTreeGlobalDebuffEffects('luck', -0.01) },
  { id:'gen_gm2_lifesteal_cap', parent:'gen_gm2_lifesteal_gate', cost:2,
    name:'Ravenous Strike',
    desc:'Noticeably increases every character\'s chance to heal on hit.',
    effect:{ type:'globalStat', stat:'lifestealChance', amount:0.01 } },
  { id:'gen_gm2_onkillheal_hub', parent:'general_hub', cost:1,
    name:'Grim Reprieve',
    desc:'Slightly increases every character\'s chance to heal on kill.',
    effect:{ type:'globalStat', stat:'onKillHealChance', amount:0.01 } },
  { id:'gen_gm2_onkillheal_c1', parent:'gen_gm2_onkillheal_hub', cost:1,
    name:'Reaper\'s Mercy',
    desc:'Further increases every character\'s chance to heal on kill.',
    effect:{ type:'globalStat', stat:'onKillHealChance', amount:0.01 } },
  { id:'gen_gm2_onkillheal_c2', parent:'gen_gm2_onkillheal_c1', cost:1,
    name:'Second Wind',
    desc:'Continues to increase every character\'s chance to heal on kill.',
    effect:{ type:'globalStat', stat:'onKillHealChance', amount:0.01 } },
  { id:'gen_gm2_onkillheal_gate', parent:'gen_gm2_onkillheal_c2', cost:1, cursed:true,
    name:'Toll of the Grim Reprieve',
    desc:'Mastering chance to heal on kill this deeply carries a price. Permanently reduces every character\'s luck by 1%. Required to reach Vital Harvest.',
    effects:
    skillTreeGlobalDebuffEffects('luck', -0.01) },
  { id:'gen_gm2_onkillheal_cap', parent:'gen_gm2_onkillheal_gate', cost:2,
    name:'Vital Harvest',
    desc:'Noticeably increases every character\'s chance to heal on kill.',
    effect:{ type:'globalStat', stat:'onKillHealChance', amount:0.02 } },
  { id:'gen_gm2_dodge_hub', parent:'general_hub', cost:1,
    name:'Light Footing',
    desc:'Slightly increases every character\'s chance to dodge an attack.',
    effect:{ type:'globalStat', stat:'dodgeChance', amount:0.01 } },
  { id:'gen_gm2_dodge_c1', parent:'gen_gm2_dodge_hub', cost:1,
    name:'Evasive Instinct',
    desc:'Further increases every character\'s chance to dodge an attack.',
    effect:{ type:'globalStat', stat:'dodgeChance', amount:0.01 } },
  { id:'gen_gm2_dodge_c2', parent:'gen_gm2_dodge_c1', cost:1,
    name:'Slippery Reflexes',
    desc:'Continues to increase every character\'s chance to dodge an attack.',
    effect:{ type:'globalStat', stat:'dodgeChance', amount:0.01 } },
  { id:'gen_gm2_dodge_gate', parent:'gen_gm2_dodge_c2', cost:1, cursed:true,
    name:'Toll of the Light Footing',
    desc:'Mastering chance to dodge an attack this deeply carries a price. Permanently reduces every character\'s luck by 1%. Required to reach Untouchable Grace.',
    effects:
    skillTreeGlobalDebuffEffects('luck', -0.01) },
  { id:'gen_gm2_dodge_cap', parent:'gen_gm2_dodge_gate', cost:2,
    name:'Untouchable Grace',
    desc:'Noticeably increases every character\'s chance to dodge an attack.',
    effect:{ type:'globalStat', stat:'dodgeChance', amount:0.02 } },
  { id:'gen_gm2_shopdiscount_hub', parent:'general_hub', cost:1,
    name:'Haggler\'s Eye',
    desc:'Slightly increases every character\'s shop discount.',
    effect:{ type:'globalStat', stat:'shopDiscountBonus', amount:0.005 } },
  { id:'gen_gm2_shopdiscount_c1', parent:'gen_gm2_shopdiscount_hub', cost:1,
    name:'Trusted Regular',
    desc:'Further increases every character\'s shop discount.',
    effect:{ type:'globalStat', stat:'shopDiscountBonus', amount:0.005 } },
  { id:'gen_gm2_shopdiscount_c2', parent:'gen_gm2_shopdiscount_c1', cost:1,
    name:'Shrewd Bargainer',
    desc:'Continues to increase every character\'s shop discount.',
    effect:{ type:'globalStat', stat:'shopDiscountBonus', amount:0.005 } },
  { id:'gen_gm2_shopdiscount_gate', parent:'gen_gm2_shopdiscount_c2', cost:1, cursed:true,
    name:'Toll of the Haggler\'s Eye',
    desc:'Mastering shop discount this deeply carries a price. Permanently reduces every character\'s luck by 1%. Required to reach Merchant\'s Favorite.',
    effects:
    skillTreeGlobalDebuffEffects('luck', -0.01) },
  { id:'gen_gm2_shopdiscount_cap', parent:'gen_gm2_shopdiscount_gate', cost:2,
    name:'Merchant\'s Favorite',
    desc:'Noticeably increases every character\'s shop discount.',
    effect:{ type:'globalStat', stat:'shopDiscountBonus', amount:0.01 } },

  { id:'gen_lw2_cursedpenny_hub', parent:'general_hub', cost:1,
    name:'Cursed Coin Sense',
    desc:'Slightly increases the odds of a cursed penny over a plain one.',
    effect:{ type:'poolWeight', pool:'COMMON_PENNY_POOL', id:'cursedpenny', bonus:1 } },
  { id:'gen_lw2_cursedpenny_c1', parent:'gen_lw2_cursedpenny_hub', cost:1,
    name:'Cursed Awareness',
    desc:'Slightly increases the odds of a cursed penny over a plain one.',
    effect:{ type:'poolWeight', pool:'COMMON_PENNY_POOL', id:'cursedpenny', bonus:1 } },
  { id:'gen_lw2_cursedpenny_c2', parent:'gen_lw2_cursedpenny_c1', cost:1,
    name:'Cursed Mastery',
    desc:'Slightly increases the odds of a cursed penny over a plain one.',
    effect:{ type:'poolWeight', pool:'COMMON_PENNY_POOL', id:'cursedpenny', bonus:1 } },
  { id:'gen_lw2_wispcoin_hub', parent:'general_hub', cost:1,
    name:'Wisp-Touched Sense',
    desc:'Slightly increases the odds of a wisp coin over a plain penny.',
    effect:{ type:'poolWeight', pool:'COMMON_PENNY_POOL', id:'wispcoin', bonus:1 } },
  { id:'gen_lw2_wispcoin_c1', parent:'gen_lw2_wispcoin_hub', cost:1,
    name:'Wisp-Touched Awareness',
    desc:'Slightly increases the odds of a wisp coin over a plain penny.',
    effect:{ type:'poolWeight', pool:'COMMON_PENNY_POOL', id:'wispcoin', bonus:1 } },
  { id:'gen_lw2_heartRed_hub', parent:'general_hub', cost:1,
    name:'Hearty Instinct',
    desc:'Slightly increases the odds of a full red heart over other heart drops.',
    effect:{ type:'poolWeight', pool:'COMMON_HEART_POOL', id:'heartRed', bonus:4 } },
  { id:'gen_lw2_heartRed_c1', parent:'gen_lw2_heartRed_hub', cost:1,
    name:'Hearty Awareness',
    desc:'Slightly increases the odds of a full red heart over other heart drops.',
    effect:{ type:'poolWeight', pool:'COMMON_HEART_POOL', id:'heartRed', bonus:4 } },
  { id:'gen_lw2_heartRed_c2', parent:'gen_lw2_heartRed_c1', cost:1,
    name:'Hearty Mastery',
    desc:'Slightly increases the odds of a full red heart over other heart drops.',
    effect:{ type:'poolWeight', pool:'COMMON_HEART_POOL', id:'heartRed', bonus:4 } },
  { id:'gen_lw2_halfheartRed_hub', parent:'general_hub', cost:1,
    name:'Modest Recovery',
    desc:'Slightly increases the odds of a half red heart from room-clear rewards.',
    effect:{ type:'poolWeight', pool:'COMMON_HEART_POOL', id:'halfheartRed', bonus:1 } },
  { id:'gen_lw2_halfheartRed_c1', parent:'gen_lw2_halfheartRed_hub', cost:1,
    name:'Modest Awareness',
    desc:'Slightly increases the odds of a half red heart from room-clear rewards.',
    effect:{ type:'poolWeight', pool:'COMMON_HEART_POOL', id:'halfheartRed', bonus:1 } },
  { id:'gen_lw2_halfheartRed_c2', parent:'gen_lw2_halfheartRed_c1', cost:1,
    name:'Modest Mastery',
    desc:'Slightly increases the odds of a half red heart from room-clear rewards.',
    effect:{ type:'poolWeight', pool:'COMMON_HEART_POOL', id:'halfheartRed', bonus:1 } },
  { id:'gen_lw2_eternalheart_hub', parent:'general_hub', cost:1,
    name:'Eternal Yearning',
    desc:'Slightly increases the odds of an eternal heart from room-clear rewards.',
    effect:{ type:'poolWeight', pool:'COMMON_HEART_POOL', id:'eternalheart', bonus:1 } },
  { id:'gen_lw2_eternalheart_c1', parent:'gen_lw2_eternalheart_hub', cost:1,
    name:'Eternal Awareness',
    desc:'Slightly increases the odds of an eternal heart from room-clear rewards.',
    effect:{ type:'poolWeight', pool:'COMMON_HEART_POOL', id:'eternalheart', bonus:1 } },
  { id:'gen_lw2_pill_hub', parent:'general_hub', cost:1,
    name:'Apothecary\'s Eye',
    desc:'Slightly increases the odds of a pill from a rare room-clear reward.',
    effect:{ type:'poolWeight', pool:'RARE_POOL', id:'pill', bonus:4 } },
  { id:'gen_lw2_pill_c1', parent:'gen_lw2_pill_hub', cost:1,
    name:'Apothecary\'s Awareness',
    desc:'Slightly increases the odds of a pill from a rare room-clear reward.',
    effect:{ type:'poolWeight', pool:'RARE_POOL', id:'pill', bonus:4 } },
  { id:'gen_lw2_pill_c2', parent:'gen_lw2_pill_c1', cost:1,
    name:'Apothecary\'s Mastery',
    desc:'Slightly increases the odds of a pill from a rare room-clear reward.',
    effect:{ type:'poolWeight', pool:'RARE_POOL', id:'pill', bonus:4 } },
  { id:'gen_lw2_trashbag_hub', parent:'general_hub', cost:1,
    name:'Scavenger\'s Nose',
    desc:'Slightly increases the odds of a trash bag from a rare room-clear reward.',
    effect:{ type:'poolWeight', pool:'RARE_POOL', id:'trashbag', bonus:1 } },
  { id:'gen_lw2_trashbag_c1', parent:'gen_lw2_trashbag_hub', cost:1,
    name:'Scavenger\'s Awareness',
    desc:'Slightly increases the odds of a trash bag from a rare room-clear reward.',
    effect:{ type:'poolWeight', pool:'RARE_POOL', id:'trashbag', bonus:1 } },
  { id:'gen_lw2_trashbag_c2', parent:'gen_lw2_trashbag_c1', cost:1,
    name:'Scavenger\'s Mastery',
    desc:'Slightly increases the odds of a trash bag from a rare room-clear reward.',
    effect:{ type:'poolWeight', pool:'RARE_POOL', id:'trashbag', bonus:1 } },
  { id:'gen_lw2_pearl_hub', parent:'general_hub', cost:1,
    name:'Pearl Diver\'s Sense',
    desc:'Slightly increases the odds of a pearl from a rare room-clear reward.',
    effect:{ type:'poolWeight', pool:'RARE_POOL', id:'pearl', bonus:1 } },
  { id:'gen_lw2_pearl_c1', parent:'gen_lw2_pearl_hub', cost:1,
    name:'Pearl Awareness',
    desc:'Slightly increases the odds of a pearl from a rare room-clear reward.',
    effect:{ type:'poolWeight', pool:'RARE_POOL', id:'pearl', bonus:1 } },
  { id:'gen_lw2_pearl_c2', parent:'gen_lw2_pearl_c1', cost:1,
    name:'Pearl Mastery',
    desc:'Slightly increases the odds of a pearl from a rare room-clear reward.',
    effect:{ type:'poolWeight', pool:'RARE_POOL', id:'pearl', bonus:1 } },
  { id:'gen_lw2_chest_hub', parent:'general_hub', cost:1,
    name:'Vaultseeker\'s Instinct',
    desc:'Slightly increases the odds of a bonus chest from a legendary room-clear reward.',
    effect:{ type:'poolWeight', pool:'LEGENDARY_POOL', id:'chest', bonus:4 } },
  { id:'gen_lw2_chest_c1', parent:'gen_lw2_chest_hub', cost:1,
    name:'Vaultseeker\'s Awareness',
    desc:'Slightly increases the odds of a bonus chest from a legendary room-clear reward.',
    effect:{ type:'poolWeight', pool:'LEGENDARY_POOL', id:'chest', bonus:4 } },
  { id:'gen_lw2_chest_c2', parent:'gen_lw2_chest_c1', cost:1,
    name:'Vaultseeker\'s Mastery',
    desc:'Slightly increases the odds of a bonus chest from a legendary room-clear reward.',
    effect:{ type:'poolWeight', pool:'LEGENDARY_POOL', id:'chest', bonus:4 } },
  { id:'gen_lw2_grey_hub', parent:'general_hub', cost:1,
    name:'Plain Curiosity',
    desc:'Slightly increases the odds of a plain grey chest whenever a chest appears.',
    effect:{ type:'poolWeight', pool:'CHEST_TYPE_POOL', id:'grey', bonus:3 } },
  { id:'gen_lw2_grey_c1', parent:'gen_lw2_grey_hub', cost:1,
    name:'Plain Awareness',
    desc:'Slightly increases the odds of a plain grey chest whenever a chest appears.',
    effect:{ type:'poolWeight', pool:'CHEST_TYPE_POOL', id:'grey', bonus:3 } },
  { id:'gen_lw2_grey_c2', parent:'gen_lw2_grey_c1', cost:1,
    name:'Plain Mastery',
    desc:'Slightly increases the odds of a plain grey chest whenever a chest appears.',
    effect:{ type:'poolWeight', pool:'CHEST_TYPE_POOL', id:'grey', bonus:3 } },
  { id:'gen_lw2_gold_hub', parent:'general_hub', cost:1,
    name:'Golden Curiosity',
    desc:'Slightly increases the odds of a golden chest whenever a chest appears.',
    effect:{ type:'poolWeight', pool:'CHEST_TYPE_POOL', id:'gold', bonus:2 } },
  { id:'gen_lw2_gold_c1', parent:'gen_lw2_gold_hub', cost:1,
    name:'Golden Awareness',
    desc:'Slightly increases the odds of a golden chest whenever a chest appears.',
    effect:{ type:'poolWeight', pool:'CHEST_TYPE_POOL', id:'gold', bonus:2 } },
  { id:'gen_lw2_gold_c2', parent:'gen_lw2_gold_c1', cost:1,
    name:'Golden Mastery',
    desc:'Slightly increases the odds of a golden chest whenever a chest appears.',
    effect:{ type:'poolWeight', pool:'CHEST_TYPE_POOL', id:'gold', bonus:2 } },
  { id:'gen_lw2_stone_hub', parent:'general_hub', cost:1,
    name:'Sturdy Curiosity',
    desc:'Slightly increases the odds of a stone chest whenever a chest appears.',
    effect:{ type:'poolWeight', pool:'CHEST_TYPE_POOL', id:'stone', bonus:2 } },
  { id:'gen_lw2_stone_c1', parent:'gen_lw2_stone_hub', cost:1,
    name:'Sturdy Awareness',
    desc:'Slightly increases the odds of a stone chest whenever a chest appears.',
    effect:{ type:'poolWeight', pool:'CHEST_TYPE_POOL', id:'stone', bonus:2 } },
  { id:'gen_lw2_stone_c2', parent:'gen_lw2_stone_c1', cost:1,
    name:'Sturdy Mastery',
    desc:'Slightly increases the odds of a stone chest whenever a chest appears.',
    effect:{ type:'poolWeight', pool:'CHEST_TYPE_POOL', id:'stone', bonus:2 } },
  { id:'gen_lw2_eternal_hub', parent:'general_hub', cost:1,
    name:'Eternal Curiosity',
    desc:'Slightly increases the odds of an eternal chest whenever a chest appears.',
    effect:{ type:'poolWeight', pool:'CHEST_TYPE_POOL', id:'eternal', bonus:1 } },
  { id:'gen_lw2_eternal_c1', parent:'gen_lw2_eternal_hub', cost:1,
    name:'Eternal Awareness',
    desc:'Slightly increases the odds of an eternal chest whenever a chest appears.',
    effect:{ type:'poolWeight', pool:'CHEST_TYPE_POOL', id:'eternal', bonus:1 } },
  { id:'gen_lw2_eternal_c2', parent:'gen_lw2_eternal_c1', cost:1,
    name:'Eternal Mastery',
    desc:'Slightly increases the odds of an eternal chest whenever a chest appears.',
    effect:{ type:'poolWeight', pool:'CHEST_TYPE_POOL', id:'eternal', bonus:1 } },
  { id:'gen_lw2_wood_hub', parent:'general_hub', cost:1,
    name:'Splintered Curiosity',
    desc:'Slightly increases the odds of a wooden chest whenever a chest appears.',
    effect:{ type:'poolWeight', pool:'CHEST_TYPE_POOL', id:'wood', bonus:1 } },
  { id:'gen_lw2_wood_c1', parent:'gen_lw2_wood_hub', cost:1,
    name:'Splintered Awareness',
    desc:'Slightly increases the odds of a wooden chest whenever a chest appears.',
    effect:{ type:'poolWeight', pool:'CHEST_TYPE_POOL', id:'wood', bonus:1 } },
  { id:'gen_lw2_wood_c2', parent:'gen_lw2_wood_c1', cost:1,
    name:'Splintered Mastery',
    desc:'Slightly increases the odds of a wooden chest whenever a chest appears.',
    effect:{ type:'poolWeight', pool:'CHEST_TYPE_POOL', id:'wood', bonus:1 } },

  { id:'gen_start_bombs2', parent:'gen_start_hub', cost:2,
    name:'Bandolier',
    desc:'Start each run with 1 more extra bomb.',
    effect:{ type:'startingPickup', pickup:'bombs', amount:1 } },
  { id:'gen_start_bombs3', parent:'gen_start_bombs2', cost:2,
    name:'Munitions Cache',
    desc:'Start each run with 1 more extra bomb.',
    effect:{ type:'startingPickup', pickup:'bombs', amount:1 } },
  { id:'gen_start_keys2', parent:'gen_start_keys', cost:2,
    name:'Master Keyring',
    desc:'Start each run with 1 more extra key.',
    effect:{ type:'startingPickup', pickup:'keys', amount:1 } },
  { id:'gen_start_keys3', parent:'gen_start_keys2', cost:2,
    name:'Skeleton Set',
    desc:'Start each run with 1 more extra key.',
    effect:{ type:'startingPickup', pickup:'keys', amount:1 } },
  { id:'gen_start_coins3', parent:'gen_start_coins2', cost:2,
    name:'Lined Pockets',
    desc:'Start each run with 2 more extra coins.',
    effect:{ type:'startingPickup', pickup:'coins', amount:1 } },
  { id:'gen_start_coins4', parent:'gen_start_coins3', cost:2,
    name:'Merchant\'s Purse',
    desc:'Start each run with 2 more extra coins.',
    effect:{ type:'startingPickup', pickup:'coins', amount:2 } },
  { id:'gen_start_blue2', parent:'gen_start_blue', cost:2,
    name:'Twin Soul Reserve',
    desc:'Start each run with 1 more extra soul (blue) heart.',
    effect:{ type:'startingPickup', pickup:'blue', amount:1 } },
  { id:'gen_start_blue3', parent:'gen_start_blue2', cost:2,
    name:'Deep Soul Reserve',
    desc:'Start each run with 1 more extra soul (blue) heart.',
    effect:{ type:'startingPickup', pickup:'blue', amount:1 } },

];

for (const n of SKILL_TREE_GENERAL_NODES) {
  SKILL_TREE_NODES.push(n);
  SKILL_TREE_NODES_BY_ID[n.id] = n;
}
