const ITEMS = {
  iron_ore: { n: 'Banded Iron Ore', c: '#9c4a3a', f: 'Hematite Fe₂O₃ + magnetite Fe₃O₄ in quartz SiO₂ bands, about 35% Fe' },
  copper_ore: { n: 'Porphyry Copper Ore', c: '#4f9a7c', f: 'Chalcopyrite CuFeS₂ and pyrite FeS₂ scattered through quartz' },
  pbzn_ore: { n: 'Lead-Zinc Ore', c: '#7d7f99', f: 'Galena PbS and sphalerite ZnS with pyrite' },
  coal: { n: 'Coal', c: '#2b2a2e', f: 'Bituminous coal, mostly carbon C with volatiles' },
  limestone: { n: 'Limestone', c: '#d8d2bd', f: 'Calcite CaCO₃' },
  sand: { n: 'Quartz Sand', c: '#e3cf8f', f: 'Silica SiO₂' },
  crushed_iron: { n: 'Crushed Iron Ore', c: '#a95c4a', f: 'Iron ore broken to gravel size' },
  crushed_copper: { n: 'Crushed Copper Ore', c: '#5fa88a', f: 'Copper ore broken to gravel size' },
  crushed_pbzn: { n: 'Crushed Lead-Zinc Ore', c: '#8b8da6', f: 'Lead-zinc ore broken to gravel size' },
  crushed_lime: { n: 'Crushed Limestone', c: '#e6e0cc', f: 'CaCO₃ gravel, used as a flux' },
  ground_iron: { n: 'Ground Iron Ore', c: '#b86b58', f: 'Fine powder: hematite, magnetite and quartz grains are now separate' },
  ground_copper: { n: 'Ground Copper Ore', c: '#70b597', f: 'Fine powder: chalcopyrite grains freed from quartz' },
  ground_pbzn: { n: 'Ground Lead-Zinc Ore', c: '#9a9cb4', f: 'Fine powder: galena and sphalerite grains freed' },
  iron_conc: { n: 'Iron Concentrate', c: '#5b2f2a', f: 'Magnetite and hematite, about 65% Fe' },
  copper_conc: { n: 'Copper Concentrate', c: '#b38a2e', f: 'Chalcopyrite CuFeS₂, about 28% Cu' },
  galena_conc: { n: 'Galena Concentrate', c: '#5f6277', f: 'Galena PbS, about 70% Pb' },
  zinc_rougher: { n: 'Zinc Rougher', c: '#a4a07a', f: 'What is left after lead flotation: sphalerite and quartz' },
  sphalerite_conc: { n: 'Sphalerite Concentrate', c: '#c2a54a', f: 'Sphalerite ZnS, about 52% Zn' },
  tailings: { n: 'Tailings', c: '#b9ae93', f: 'Ground quartz waste left after separation' },
  coke: { n: 'Coke', c: '#4a4650', f: 'Nearly pure carbon C, coal with the volatiles baked out' },
  quicklime: { n: 'Quicklime', c: '#f4f1e8', f: 'Calcium oxide CaO' },
  slag: { n: 'Slag', c: '#5c5a52', f: 'Glassy silicates such as CaSiO₃ and Fe₂SiO₄ (fayalite)' },
  pig_iron: { n: 'Pig Iron', c: '#7b7f86', f: 'Fe with about 4% C, brittle' },
  steel: { n: 'Steel', c: '#a9b3bf', f: 'Fe with under 1% C, strong and ductile' },
  copper_calcine: { n: 'Copper Calcine', c: '#7a4a2a', f: 'Roasted concentrate: Cu₂S and FeO' },
  copper_matte: { n: 'Copper Matte', c: '#5a3a2a', f: 'Molten Cu₂S·FeS, about 60% Cu' },
  blister_copper: { n: 'Blister Copper', c: '#c46a3a', f: 'Cu about 98.5%, full of SO₂ bubbles' },
  copper_cathode: { n: 'Copper Cathode', c: '#e07a4a', f: 'Cu 99.99%' },
  anode_slime: { n: 'Anode Slime', c: '#4a4a3a', f: 'Sludge from copper refining with Au, Ag, Se and Te' },
  lead_oxide: { n: 'Lead Oxide Sinter', c: '#c9b26a', f: 'Lead(II) oxide PbO' },
  lead: { n: 'Lead Bullion', c: '#6a6f80', f: 'Pb, soft and very dense' },
  zinc_calcine: { n: 'Zinc Calcine', c: '#e8e2d0', f: 'Zinc oxide ZnO' },
  zinc: { n: 'Zinc Cathode', c: '#b8c2c8', f: 'Zn 99.99%' },
  casting: { n: 'Iron Casting', c: '#6d7178', f: 'Cast pig iron parts: gears, frames, pipe' },
  plate: { n: 'Steel Plate', c: '#c3ccd6', f: 'Rolled steel sheet' },
  wire: { n: 'Copper Wire', c: '#e8955f', f: 'Drawn Cu wire' },
  motor: { n: 'Electric Motor', c: '#5a7fa8', f: 'Copper windings on a steel frame' },
  brick: { n: 'Refractory Brick', c: '#c98a5a', f: 'Silica brick bonded with lime, survives 1700°C' },
  lead_sheet: { n: 'Lead Sheet', c: '#7b8094', f: 'Pb sheet, resists sulfuric acid' },
  brass: { n: 'Brass', c: '#d6b04a', f: 'Cu-Zn alloy, about 65/35' },
  rock_salt: { n: 'Rock Salt', c: '#d9c9c4', f: 'Halite NaCl with a little gypsum and clay' },
  bauxite: { n: 'Bauxite', c: '#b5653a', f: 'Gibbsite Al(OH)₃ with hematite Fe₂O₃ and kaolinite clay' },
  mineral_sand: { n: 'Mineral Sand', c: '#3a3530', f: 'Beach sand rich in ilmenite FeTiO₃, rutile TiO₂, zircon ZrSiO₄ and monazite' },
  salt: { n: 'Salt', c: '#f2eee8', f: 'Sodium chloride NaCl' },
  sodium: { n: 'Sodium', c: '#c8c8b8', f: 'Na metal, soft and violently reactive with water. Stored under oil' },
  crushed_bauxite: { n: 'Crushed Bauxite', c: '#c4764a', f: 'Bauxite ground fine for digestion' },
  red_mud: { n: 'Red Mud', c: '#9a3a22', f: 'Caustic residue of Fe₂O₃, TiO₂ and sodium aluminosilicate' },
  al_hydroxide: { n: 'Aluminium Hydroxide', c: '#f0f0f4', f: 'Gibbsite Al(OH)₃ crystals precipitated from the liquor' },
  alumina: { n: 'Alumina', c: '#fafafa', f: 'Aluminium oxide Al₂O₃, a white powder' },
  anode: { n: 'Carbon Anode', c: '#38363c', f: 'Baked block of petroleum coke and pitch, burned away in the pot' },
  aluminium: { n: 'Aluminium', c: '#c8d0dc', f: 'Al 99.7%, light and corrosion resistant' },
  gallium: { n: 'Gallium', c: '#a8b8c8', f: 'Ga metal, melts in your hand at 30°C. Recovered from Bayer liquor' },
  heavy_conc: { n: 'Heavy Mineral Concentrate', c: '#2a2622', f: 'The dense grains of mineral sand: ilmenite, rutile, zircon, monazite' },
  ilmenite: { n: 'Ilmenite', c: '#1e1c1c', f: 'FeTiO₃, weakly magnetic' },
  nonmag: { n: 'Non-Magnetic Heavies', c: '#8a6a4a', f: 'Rutile, zircon and monazite left after magnetic separation' },
  rutile: { n: 'Rutile', c: '#7a2a1a', f: 'Titanium dioxide TiO₂, conducts weakly when hot' },
  zircon: { n: 'Zircon', c: '#e8dcc0', f: 'ZrSiO₄, melts at 2550°C. Prized refractory' },
  monazite: { n: 'Monazite', c: '#c8a040', f: '(Ce,La,Nd,Th)PO₄, rare earth phosphate, slightly radioactive from thorium' },
  ti_slag: { n: 'Titania Slag', c: '#3a3036', f: 'About 85% TiO₂, the iron smelted out of ilmenite' },
  titanium: { n: 'Titanium Sponge', c: '#9aa0aa', f: 'Porous Ti metal from the Hunter process' },
  pyrite_conc: { n: 'Pyrite Concentrate', c: '#c8b048', f: "Fool's gold FeS₂, floated off the copper ore" },
  pyrite_cinder: { n: 'Pyrite Cinder', c: '#8a3a2a', f: 'Fe₂O₃ left after roasting pyrite, a usable iron ore' },
  dore: { n: 'Doré Bead', c: '#d8c890', f: 'Silver-gold alloy melted out of anode slime' },
  silver: { n: 'Silver', c: '#e0e4ea', f: 'Ag 99.9%' },
  gold: { n: 'Gold', c: '#f0c040', f: 'Au 99.99%' },
  selenium: { n: 'Selenium', c: '#6a2a2a', f: 'Se, red-grey. Used in glass and solar cells' },
  gypsum: { n: 'Gypsum', c: '#ece6da', f: 'Calcium sulfate dihydrate CaSO₄·2H₂O, the solid end of flue gas scrubbing' },
  bleach: { n: 'Bleach', c: '#d8e8a0', f: 'Sodium hypochlorite NaOCl solution in drums, a strong oxidiser' },
  clinker: { n: 'Cement Clinker', c: '#6a6660', f: 'Nodules of calcium silicates Ca₃SiO₅ and Ca₂SiO₄ fused at 1450°C' },
  cement: { n: 'Portland Cement', c: '#a8a8a4', f: 'Clinker ground with a little gypsum, which stops it setting in seconds' },
  caliche: { n: 'Caliche', c: '#d8c8a8', f: 'Chilean desert crust: sodium nitrate NaNO₃ with salt, gypsum and a little iodate, cemented into rock' },
  sodium_nitrate: { n: 'Sodium Nitrate', c: '#f0ecdc', f: 'Chile saltpetre NaNO₃, an oxidiser. Half the world\'s explosives and fertiliser came from it before 1913' },
  crushed_caliche: { n: 'Crushed Caliche', c: '#e0d4b8', f: 'Caliche broken small for leaching' },
  sulfur: { n: 'Sulfur', c: '#f0d830', f: 'Elemental S, yellow and brittle. Burns with a blue flame to SO₂' },
  black_powder: { n: 'Blasting Powder', c: '#3a3836', f: 'Sodium nitrate, sulfur and charcoal, about 72/13/15. Burns fast and makes hot gas' },
  cartridge: { n: 'Lead Shot Cartridge', c: '#c8a040', f: 'Brass case, a charge of powder and a lead slug. Ten rounds per box' },
  cylinder: { n: 'Steel Cylinder', c: '#7a8a7a', f: 'Seamless steel gas bottle, tested to 250 bar' },
  cl2_cyl: { n: 'Chlorine Cylinder', c: '#b8d84a', f: 'Liquid Cl₂ under its own vapour pressure, about 7 bar. Released, it boils into a cloud 2.5 times heavier than air that creeps along the ground' },
  nh3_cyl: { n: 'Ammonia Cylinder', c: '#a8c8e8', f: 'Liquid NH₃ at about 9 bar. A base: it neutralises the sulfuric acid in crawler blood. Lighter than air, so the cloud rises and blows away fast' },
  amm_nitrate: { n: 'Ammonium Nitrate', c: '#f4f4ec', f: 'NH₄NO₃ prills. Fertiliser, and an oxidiser that detonates when confined with fuel' },
  ammonal: { n: 'Ammonal', c: '#c8c8c0', f: 'Ammonium nitrate with aluminium powder and charcoal. The aluminium burns to Al₂O₃ and makes the blast far hotter' },
  he_drum: { n: 'Ammonal Drum', c: '#8a5a3a', f: 'A steel drum packed with ammonal and a black powder burster' },
  amm_sulfate: { n: 'Ammonium Sulfate', c: '#ece8f0', f: '(NH₄)₂SO₄ crystals, a nitrogen fertiliser made by scrubbing SO₂ with ammonia' },
  pt_gauze: { n: 'Platinum Gauze', c: '#d8dce4', f: 'Woven Pt-Rh wire, 90/10. Catalyses ammonia burning to NO at 900°C. Nobody here can make it, so it comes from the old works' },
  concrete: { n: 'Concrete Block', c: '#bcbab4', f: 'Cement, sand and water. Calcium silicate hydrate binds the grains' },
  pitch: { n: 'Coal Tar Pitch', c: '#1c1a1e', f: 'The black residue left in the still. Binds carbon anodes and electrodes' },
  nahco3: { n: 'Sodium Bicarbonate', c: '#f4f2ea', f: 'NaHCO₃ crystals filtered from the Solvay tower' },
  soda_ash: { n: 'Soda Ash', c: '#ecebe2', f: 'Sodium carbonate Na₂CO₃, the alkali behind glass, soap and paper' },
  cacl2: { n: 'Calcium Chloride', c: '#d8dcd0', f: 'CaCl₂, the waste of the Solvay process. Melts road ice, otherwise dumped' },
  glass: { n: 'Glass', c: '#a8d8d8', f: 'Soda-lime glass: about 73% SiO₂, 14% Na₂O, 9% CaO. Shrugs off acids, but hot caustic slowly dissolves it' },
  tnt: { n: 'TNT', c: '#e8d070', f: '2,4,6-Trinitrotoluene C₇H₅N₃O₆. Pale yellow flakes that melt at 80°C and can be poured into shells. Hard to set off by accident' },
  shell: { n: 'HE Shell', c: '#b08a40', f: 'A forged steel shell filled with cast TNT, in a brass case with a black powder charge' },
  carbon: { n: 'Activated Carbon', c: '#2a2a2e', f: 'Coke etched by steam at 900°C into a sponge of pores. One gram holds about 1000 m² of internal surface' },
  phos_cyl: { n: 'Phosgene Cylinder', c: '#d8d8c0', f: 'Liquid COCl₂ at about 2 bar. Colourless, smells of mown hay, and its damage shows only hours later' },
  phosphate_rock: { n: 'Phosphate Rock', c: '#8a7a5a', f: 'Fluorapatite Ca₅(PO₄)₃F laid down in old sea floors, about 30% P₂O₅, with quartz and a little uranium' },
  crushed_phos: { n: 'Crushed Phosphate', c: '#a8987a', f: 'Phosphate rock broken to gravel size' },
  phosphorus: { n: 'White Phosphorus', c: '#f0ecd0', f: 'P₄, a waxy yellow-white solid that catches fire by itself in air above 30°C, so it is cast and shipped under water' },
  wp_shell: { n: 'WP Shell', c: '#e8e4d8', f: 'A steel shell packed with white phosphorus around a small burster. It scatters burning wedges at 800°C that stick, smoulder and reignite' },
  fluorspar: { n: 'Fluorspar', c: '#b8a8d8', f: 'Calcium fluoride CaF₂, the mineral that gave fluorescence its name' },
  v_pig: { n: 'Vanadium Pig Iron', c: '#6a6e78', f: 'Iron smelted from titanium-rich ore. It carries 1-2% vanadium that a converter can blow into its own slag' },
  v_slag: { n: 'Vanadium Slag', c: '#4a4a3a', f: 'About 15% V₂O₃ held in iron silicate. Titanomagnetite smelters in South Africa, Russia and China make most of the world\'s vanadium this way' },
  na_vanadate: { n: 'Sodium Vanadate Calcine', c: '#a89048', f: 'NaVO₃ roasted out of slag with soda ash. It dissolves in water and the gangue does not' },
  amv: { n: 'Ammonium Metavanadate', c: '#f0e8c8', f: 'NH₄VO₃, a white powder that falls out when ammonium chloride is added to vanadate liquor' },
  v2o5: { n: 'Vanadium Pentoxide', c: '#e0a020', f: 'V₂O₅, orange-brown. It swaps oxygen back and forth between V⁵⁺ and V⁴⁺, which is why it catalyses SO₂ oxidation' },
  v_cat: { n: 'V₂O₅ Catalyst Rings', c: '#c88a30', f: 'Vanadium pentoxide on a porous silica carrier, pressed into rings so gas flows through the bed. Each charge slowly loses activity' },
  spent_v_cat: { n: 'Spent V₂O₅ Catalyst', c: '#6a5a3a', f: 'Catalyst rings clogged with dust and sintered by heat. The vanadium is still there and can be leached back out' },
  fe_cat: { n: 'Fused Iron Catalyst', c: '#4a4c54', f: 'Magnetite melted with alumina and lime, then crushed. Alois Mittasch tried 20,000 recipes in 1909-1912 to find it, and it is still used' },
  v_steel: { n: 'Vanadium Steel', c: '#8a96a8', f: 'Steel with 0.2% vanadium. Fine vanadium carbides pin the grains, so it is far stronger and tougher. Ford built the Model T from it' },
  bitumen: { n: 'Bitumen', c: '#141210', f: 'The heaviest residue at the bottom of the crude column. Too thick to boil, it paves roads and roofs, or is coked' },
  pet_coke: { n: 'Petroleum Coke', c: '#2a2a30', f: 'Nearly pure carbon baked out of bitumen in a delayed coker. Low in ash, so it makes the best carbon anodes' },
  polyethylene: { n: 'Polyethylene Pellets', c: '#eef0ea', f: '(C₂H₄)ₙ, long chains of ethylene. Discovered by accident at ICI in 1933 when a trace of oxygen set off a high-pressure run' },
  pvc: { n: 'PVC Resin', c: '#e0e4dc', f: 'Polyvinyl chloride (C₂H₃Cl)ₙ, a white powder. More than half of it is chlorine from salt, so it needs less oil than other plastics' },
  sylvinite: { n: 'Sylvinite', c: '#c87a6a', f: 'Red-flecked evaporite: potash KCl and halite NaCl laid down as an ancient sea dried out. Iron oxide in the sylvite turns it pink' },
  crushed_sylv: { n: 'Crushed Sylvinite', c: '#d89a8a', f: 'Sylvinite broken fine enough that the KCl and NaCl crystals come apart' },
  potash: { n: 'Potash', c: '#e8b0a0', f: 'Muriate of potash, about 95% KCl. Plants need potassium to open and close the pores in their leaves' },
  ssp: { n: 'Single Superphosphate', c: '#c8c0a8', f: 'Ca(H₂PO₄)₂ mixed with gypsum, about 20% P₂O₅. John Lawes patented it in 1842 and it began the fertiliser industry' },
  tsp: { n: 'Triple Superphosphate', c: '#a8a088', f: 'Ca(H₂PO₄)₂ with no gypsum, about 46% P₂O₅. Phosphoric acid in place of sulfuric acid leaves no dead weight to ship' },
  dap: { n: 'Diammonium Phosphate', c: '#8a8070', f: '(NH₄)₂HPO₄ granules, 18-46-0. The most traded fertiliser in the world' },
  urea: { n: 'Urea', c: '#f4f4f0', f: 'CO(NH₂)₂ prills, 46% nitrogen. Friedrich Wöhler made it from inorganic salts in 1828, ending the idea that only life could make organic compounds' },
  npk: { n: 'NPK Compound', c: '#b0c890', f: 'Granules that carry nitrogen, phosphorus and potassium together, here 15-15-15, so a farmer spreads one bag instead of three' },
  cryolite: { n: 'Cryolite', c: '#e8eef0', f: 'Sodium hexafluoroaluminate Na₃AlF₆. Molten, it dissolves alumina like water dissolves salt' },
};

const FLUIDS = {
  water: { n: 'Water', c: '#3a7fd0', f: 'H₂O', cp: 4.18, t: 15 },
  steam: { n: 'Steam', c: '#d8dde4', f: 'Saturated H₂O vapour, 165°C at 7 bar', gas: true, cp: 2.0, t: 165 },
  co2: { n: 'Carbon Dioxide', c: '#8a8f99', f: 'CO₂ flue gas, leaves the furnace at about 250°C', gas: true, cp: 0.85, t: 250 },
  so2: { n: 'Sulfur Dioxide', c: '#d8c84a', f: 'SO₂, choking and toxic, leaves the roaster at about 350°C', gas: true, cp: 0.64, t: 350 },
  acid: { n: 'Sulfuric Acid', c: '#e0a03a', f: 'H₂SO₄ diluted for leaching, about 70°C. Dilute acid dissolves iron', cp: 1.4, t: 70, corr: 1, ck: 'acid' },
  znso4: { n: 'Zinc Sulfate Solution', c: '#9ad0c0', f: 'ZnSO₄ in slightly acidic water, about 50°C', cp: 3.6, t: 50, corr: 0.3, ck: 'acid' },
  brine: { n: 'Brine', c: '#8ab8d8', f: 'Saturated NaCl in water, slowly rusts plain iron', cp: 3.3, t: 15, corr: 0.15, ck: 'cl' },
  naoh: { n: 'Caustic Soda', c: '#d0d8f0', f: 'NaOH solution, about 30%. Dissolves lead and aluminium', cp: 3.5, t: 60, corr: 0.6, ck: 'alk' },
  cl2: { n: 'Chlorine', c: '#b8d84a', f: 'Cl₂, a heavy yellow-green poison. Wet chlorine attacks most metals', gas: true, cp: 0.48, t: 80, corr: 0.8, ck: 'cl' },
  h2: { n: 'Hydrogen', c: '#e8f0ff', f: 'H₂, the lightest gas. Burns to water', gas: true, cp: 14.3, t: 80 },
  liquor: { n: 'Aluminate Liquor', c: '#c88a6a', f: 'Sodium aluminate NaAl(OH)₄ in hot caustic, about 145°C', cp: 3.4, t: 145, corr: 0.6, ck: 'alk' },
  nh3: { n: 'Ammonia', c: '#a8c8e8', f: 'NH₃, a pungent alkaline gas. Fine in steel, but it eats copper and brass', gas: true, cp: 2.1, t: 40, corr: 0.1, ck: 'alk' },
  hno3: { n: 'Nitric Acid', c: '#e8d070', f: 'HNO₃ about 60%, yellow from dissolved NO₂. It dissolves lead outright, so it needs titanium or a passive metal', cp: 2.7, t: 40, corr: 1, ck: 'nit' },
  ticl4: { n: 'Titanium Tetrachloride', c: '#e8e0c8', f: 'TiCl₄, a fuming liquid that hydrolyses to HCl in moist air', cp: 0.77, t: 60, corr: 0.2, ck: 'cl' },
  tar: { n: 'Coal Tar', c: '#3a2e26', f: 'Black, sticky condensate from coke oven gas. Holds benzene, toluene, phenol, naphthalene and pitch', cp: 1.6, t: 80 },
  coalgas: { n: 'Coke Oven Gas', c: '#b0a8a0', f: 'About 55% hydrogen and 25% methane, plus CO. The town gas that lit Victorian streets', gas: true, cp: 2.4, t: 60 },
  toluene: { n: 'Toluene', c: '#e0d8b8', f: 'C₆H₅CH₃, a clear solvent boiling at 111°C. The light oil cut of coal tar', cp: 1.7, t: 30 },
  nh4cl: { n: 'Ammonium Chloride Liquor', c: '#c8d8c8', f: 'NH₄Cl solution from the Solvay tower. Chloride attacks plain steel', cp: 3.5, t: 30, corr: 0.4, ck: 'cl' },
  co: { n: 'Producer Gas', c: '#9a8a7a', f: 'Carbon monoxide made by passing CO₂ or steam over white-hot coke. Odourless and deadly, it burns with a blue flame', gas: true, cp: 1.04, t: 400 },
  phosgene: { n: 'Phosgene', c: '#d8d8c0', f: 'COCl₂, a heavy gas 3.4 times denser than air. Moisture splits it into HCl, which eats steel', gas: true, cp: 0.6, t: 60, corr: 0.6, ck: 'cl' },
  sif4: { n: 'Silicon Tetrafluoride', c: '#c8c0d8', f: 'SiF₄ fume from heating fluorapatite with silica. Moist air turns it to fluorosilicic acid that etches glass and scorches leaves for miles', gas: true, cp: 0.75, t: 120, corr: 0.8, ck: 'hf' },
  h2sif6: { n: 'Fluorosilicic Acid', c: '#b8c8d0', f: 'H₂SiF₆ solution from scrubbing SiF₄ with water. Eats glass and titanium; lead and rubber hold it', cp: 3.3, t: 40, corr: 0.6, ck: 'hf' },
  hf: { n: 'Hydrofluoric Acid', c: '#d0e0d8', f: 'HF about 70%. Dissolves glass, titanium and skin, and seeps through to the bone. Lead resists it', cp: 2.5, t: 25, corr: 1.2, ck: 'hf' },
  crude: { n: 'Crude Oil', c: '#2a2218', f: 'A brown-black mix of thousands of hydrocarbons, from methane gas to tar. It comes up warm from the rock', cp: 2.0, t: 45 },
  fuel_gas: { n: 'Refinery Fuel Gas', c: '#c8c0b0', f: 'Mostly methane with ethane and propane. Refineries burn their own gas in furnaces and boilers', gas: true, cp: 2.2, t: 40 },
  naphtha: { n: 'Naphtha', c: '#e8d8a0', f: 'Light liquid hydrocarbons boiling at 30-180°C, C₅ to C₁₀. Feed for steam crackers and petrol', cp: 2.1, t: 40 },
  gas_oil: { n: 'Gas Oil', c: '#a87a30', f: 'Middle distillate boiling at 250-350°C. Diesel and heating oil', cp: 2.0, t: 60 },
  ethylene: { n: 'Ethylene', c: '#d8e8f0', f: 'C₂H₄, the most-made organic chemical on Earth. Its double bond opens easily, so it links into chains', gas: true, cp: 1.5, t: 40 },
  edc: { n: 'Ethylene Dichloride', c: '#d0d8a8', f: 'C₂H₄Cl₂, a heavy oily liquid. Traces of HCl in it eat steel', cp: 1.3, t: 50, corr: 0.3, ck: 'cl' },
  vcm: { n: 'Vinyl Chloride', c: '#c8e0c0', f: 'C₂H₃Cl gas, kept liquid under pressure. A carcinogen: plants run it in sealed loops', gas: true, cp: 0.9, t: 40 },
  hcl: { n: 'Hydrogen Chloride', c: '#b8d8a0', f: 'HCl gas. With any moisture it becomes hydrochloric acid, which dissolves steel and titanium', gas: true, cp: 0.8, t: 60, corr: 0.9, ck: 'cl' },
  h2s: { n: 'Hydrogen Sulfide', c: '#c8c070', f: 'H₂S, the rotten-egg gas stripped out of sour oil. Deadens the sense of smell at dangerous levels', gas: true, cp: 1.0, t: 50 },
  diesel: { n: 'Diesel', c: '#d8b848', f: 'Hydrotreated gas oil with the sulfur taken out. Burns clean in compression-ignition engines', cp: 2.0, t: 40 },
  bfw: { n: 'Softened Water', c: '#8ac8f0', f: 'Water with its calcium hardness precipitated out. Boilers fed with it stay free of scale', cp: 4.18, t: 15 },
  h3po4: { n: 'Phosphoric Acid', c: '#c8b878', f: 'Green-black wet-process H₃PO₄, about 30% P₂O₅, full of fluoride and iron. Attacks steel; lead and rubber hold it', cp: 2.6, t: 75, corr: 0.6, ck: 'acid' },
};

const ORES = [
  null,
  { item: 'iron_ore', c: '#8a4a3c', s: '#c06a50' },
  { item: 'copper_ore', c: '#3f7a64', s: '#7fd0a8' },
  { item: 'pbzn_ore', c: '#5f6177', s: '#b0b4d0' },
  { item: 'coal', c: '#242226', s: '#4a4850' },
  { item: 'limestone', c: '#b8b29d', s: '#eae4d0' },
  { item: 'sand', c: '#c7b273', s: '#f0e0a8' },
  { item: 'rock_salt', c: '#b88a9c', s: '#f6dce6' },
  { item: 'bauxite', c: '#c0702a', s: '#f0b060' },
  { item: 'mineral_sand', c: '#4a4036', s: '#e0c050' },
  { item: 'caliche', c: '#b0a080', s: '#f4ecd0' },
  { item: 'phosphate_rock', c: '#6a5c44', s: '#c8b890' },
  { item: 'crude', c: '#17130f', s: '#5a4a78', fluid: true },
  { item: 'sylvinite', c: '#9a5a50', s: '#f0c0b0' },
];

const BUILD = {
  belt: { n: 'Belt', kind: 'belt', w: 1, h: 1, cat: 'Logistics', c: '#c9a23a', cost: { casting: 1 }, makes: 2, d: 'Moves items 2 tiles/s. Drag to lay a line.' },
  sorter: { n: 'Sorter', kind: 'sorter', w: 1, h: 1, cat: 'Logistics', c: '#d07a3a', ab: 'SO', cost: { casting: 2, wire: 2, brass: 1 }, d: 'Sends the filtered item forward and everything else to the right.' },
  chest: { n: 'Chest', kind: 'chest', w: 1, h: 1, cat: 'Logistics', c: '#8a6a3a', ab: 'CH', cost: { casting: 4 }, d: 'Stores 400 items and feeds neighbouring machines and outgoing belts.' },
  pipe: { n: 'Cast Iron Pipe', kind: 'pipe', w: 1, h: 1, cat: 'Logistics', c: '#6a7a8a', cost: { casting: 1 }, makes: 2, d: 'DN50, rated 16 bar. Cheap and brittle: it cracks at once when overpressured or hit by a sudden temperature change.', P: { mat: 'Grey cast iron', dn: 50, v: 100, g: 200, q: 120, bar: 16, tmax: 400, duct: 0, shock: 45, cw: 60, ua: 0.3, res: '' } },
  steel_pipe: { n: 'Steel Pipe', kind: 'pipe', w: 1, h: 1, cat: 'Logistics', c: '#9aa8b6', cost: { plate: 1 }, makes: 1, d: 'DN100, rated 40 bar. Four times the flow of DN50. Ductile: it bulges before it bursts. Handles caustic, but dilute acid and wet chlorine eat it.', P: { mat: 'Carbon steel', dn: 100, v: 250, g: 800, q: 400, bar: 40, tmax: 550, duct: 2, cw: 90, ua: 0.4, res: 'alk' } },
  lead_pipe: { n: 'Lead-Lined Pipe', kind: 'pipe', w: 1, h: 1, cat: 'Logistics', c: '#7a7f9a', cost: { lead_sheet: 1, casting: 1 }, makes: 2, d: 'DN50, rated only 6 bar. The lead lining shrugs off sulfuric acid and chlorides but softens above 250°C, and caustic soda dissolves it. Lead also holds fluorides that destroy glass.', P: { mat: 'Steel with lead lining', dn: 50, v: 100, g: 200, q: 120, bar: 6, tmax: 250, duct: 4, cw: 30, ua: 0.3, res: 'acid cl hf', lined: 'lead' } },
  ti_pipe: { n: 'Titanium Pipe', kind: 'pipe', w: 1, h: 1, cat: 'Logistics', c: '#a8b0c0', cost: { titanium: 1 }, makes: 1, d: 'DN100, rated 35 bar. Its oxide skin makes it immune to chlorine, brine, caustic and nitric acid, but hot sulfuric acid strips it and fluorides dissolve it three times faster than steel.', P: { mat: 'Titanium grade 2', dn: 100, v: 250, g: 800, q: 400, bar: 35, tmax: 450, duct: 3, cw: 50, ua: 0.3, res: 'cl alk nit', weak: 'hf' } },
  glass_pipe: { n: 'Glass-Lined Pipe', kind: 'pipe', w: 1, h: 1, cat: 'Logistics', c: '#7ab8b8', cost: { glass: 1, casting: 1 }, makes: 2, d: 'DN50, rated 10 bar. A fused glass enamel inside steel resists every acid and chloride. But a sudden temperature change cracks the glass, and caustic soda slowly dissolves it. Fluorides etch through glass three times faster than steel.', P: { mat: 'Steel with glass enamel', dn: 50, v: 100, g: 200, q: 120, bar: 10, tmax: 230, duct: 0, shock: 35, cw: 40, ua: 0.3, res: 'acid cl nit', weak: 'hf', lined: 'glass' } },
  booster: { n: 'Booster Pump', kind: 'booster', w: 1, h: 1, cat: 'Logistics', c: '#4a7ab0', ab: 'BP', kw: 30, cost: { casting: 2, motor: 1 }, d: 'Takes fluid from the pipe behind it and pushes it forward up to the outlet pressure you set. Fluid cannot flow back through it.' },
  miner: { n: 'Miner', kind: 'miner', w: 2, h: 2, cat: 'Mining', c: '#7a6a4a', ab: 'MI', kw: 90, cost: { casting: 5, plate: 3, motor: 2 }, d: 'Digs the ore under it, one every 2s.' },
  pump: { n: 'Offshore Pump', kind: 'pump', w: 1, h: 1, cat: 'Mining', c: '#3a6aa0', ab: 'PU', cost: { casting: 3, motor: 1 }, d: 'Place on water. Pumps 60 water/s.' },
  boiler: { n: 'Boiler', kind: 'machine', w: 2, h: 2, cat: 'Power', c: '#9a5a3a', ab: 'BO', cost: { brick: 5, casting: 4 }, d: 'Burns fuel to turn water into steam.' },
  engine: { n: 'Steam Engine', kind: 'engine', w: 2, h: 2, cat: 'Power', c: '#6a7a6a', ab: 'SE', cost: { casting: 6, plate: 4, motor: 2 }, d: 'Makes up to 900 kW from 30 steam/s.' },
  crusher: { n: 'Jaw Crusher', kind: 'machine', w: 2, h: 2, cat: 'Processing', c: '#7a7a6a', ab: 'CR', kw: 60, cost: { casting: 6, motor: 2 }, d: 'Breaks rock into gravel.' },
  mill: { n: 'Ball Mill', kind: 'machine', w: 2, h: 2, cat: 'Processing', c: '#6a7a8a', ab: 'BM', kw: 120, cost: { plate: 8, motor: 2 }, d: 'Grinds gravel with water and steel balls until the mineral grains come free.' },
  magsep: { n: 'Magnetic Separator', kind: 'machine', w: 2, h: 2, cat: 'Processing', c: '#5a5a8a', ab: 'MS', kw: 60, cost: { plate: 4, wire: 6, motor: 1 }, d: 'Pulls magnetic iron minerals out of the quartz.' },
  flotation: { n: 'Flotation Cell', kind: 'machine', w: 2, h: 2, cat: 'Processing', c: '#4a8a8a', ab: 'FL', kw: 80, cost: { plate: 6, motor: 1 }, d: 'Bubbles carry water-repelling sulfide grains to the froth while quartz sinks.' },
  coke_oven: { n: 'Coke Oven', kind: 'machine', w: 2, h: 2, cat: 'Smelting', c: '#5a4a4a', ab: 'CO', cost: { brick: 10 }, d: 'Bakes coal without air into coke.' },
  kiln: { n: 'Lime Kiln', kind: 'machine', w: 2, h: 2, cat: 'Smelting', c: '#b0a080', ab: 'LK', cost: { brick: 8, plate: 2 }, d: 'Burns limestone into quicklime.' },
  roaster: { n: 'Roaster', kind: 'machine', w: 2, h: 2, cat: 'Smelting', c: '#a06a3a', ab: 'RO', kw: 30, cost: { brick: 8, plate: 4 }, d: 'Burns sulfur out of sulfide concentrates. Gives off SO₂.' },
  blast: { n: 'Blast Furnace', kind: 'machine', w: 3, h: 3, cat: 'Smelting', c: '#7a3a2a', ab: 'BF', cost: { brick: 20, casting: 10 }, d: 'Reduces oxides with coke.' },
  converter: { n: 'Converter', kind: 'machine', w: 2, h: 2, cat: 'Smelting', c: '#8a5a4a', ab: 'CV', cost: { brick: 12, plate: 6 }, d: 'Blows air through molten metal to burn out impurities.' },
  smelter: { n: 'Flash Smelter', kind: 'machine', w: 3, h: 3, cat: 'Smelting', c: '#9a4a3a', ab: 'FS', kw: 50, cost: { brick: 20, plate: 8 }, d: 'Melts copper calcine with silica flux into matte.' },
  acid_plant: { n: 'Acid Plant', kind: 'machine', w: 3, h: 3, cat: 'Chemistry', c: '#b08a3a', ab: 'AP', kw: 50, cost: { lead_sheet: 10, plate: 6, motor: 2 }, d: 'Turns SO₂ into sulfuric acid.' },
  leach: { n: 'Leach Tank', kind: 'machine', w: 2, h: 2, cat: 'Chemistry', c: '#5a9a8a', ab: 'LT', kw: 40, cost: { lead_sheet: 6, plate: 2 }, d: 'Dissolves metal oxides in acid.' },
  electro: { n: 'Electrolysis Cell', kind: 'machine', w: 2, h: 2, cat: 'Chemistry', c: '#4a6ab0', ab: 'EC', kw: 300, cost: { lead_sheet: 6, wire: 10 }, d: 'Drives reactions with electric current: plates pure metal onto cathodes, splits brine, or splits molten salt.' },
  workshop: { n: 'Workshop', kind: 'machine', w: 2, h: 2, cat: 'Processing', c: '#6a5a7a', ab: 'WS', kw: 75, cost: { casting: 6, motor: 2 }, d: 'Makes parts from metals.' },
  digester: { n: 'Digester', kind: 'machine', w: 2, h: 2, cat: 'Chemistry', c: '#a8604a', ab: 'DG', kw: 60, cost: { plate: 10, motor: 1 }, d: 'Pressure vessel that dissolves alumina out of bauxite with hot caustic soda.' },
  precipitator: { n: 'Precipitator', kind: 'machine', w: 2, h: 2, cat: 'Chemistry', c: '#b0b8c8', ab: 'PR', kw: 30, cost: { plate: 8, motor: 1 }, d: 'Cools the liquor and seeds it so aluminium hydroxide crystallises out.' },
  pot: { n: 'Reduction Pot', kind: 'machine', w: 3, h: 3, cat: 'Smelting', c: '#5a6a7a', ab: 'HH', kw: 600, cost: { brick: 12, plate: 6, wire: 20 }, d: 'Hall-Héroult cell: alumina dissolved in molten cryolite is split by a huge current.' },
  spiral: { n: 'Gravity Spiral', kind: 'machine', w: 2, h: 2, cat: 'Processing', c: '#8a8a7a', ab: 'GS', kw: 20, cost: { plate: 4, casting: 2 }, d: 'Slurry runs down a helix; heavy grains hug the inside, light quartz is flung out.' },
  esep: { n: 'Electrostatic Separator', kind: 'machine', w: 2, h: 2, cat: 'Processing', c: '#6a6aa0', ab: 'ES', kw: 60, cost: { plate: 4, wire: 10, motor: 1 }, d: 'Charged rolls throw conducting grains (rutile) away from insulators (zircon).' },
  arc: { n: 'Electric Arc Furnace', kind: 'machine', w: 3, h: 3, cat: 'Smelting', c: '#6a4a6a', ab: 'EA', kw: 500, cost: { brick: 15, plate: 6, wire: 15 }, d: 'Graphite electrodes strike an arc that melts anything.' },
  chlorinator: { n: 'Chlorinator', kind: 'machine', w: 2, h: 2, cat: 'Chemistry', c: '#9ab04a', ab: 'CL', kw: 40, cost: { brick: 10, plate: 6 }, d: 'Fluidised bed where chlorine and coke turn titanium oxide into volatile TiCl₄.' },
  scrubber: { n: 'Gas Scrubber', kind: 'machine', w: 2, h: 2, cat: 'Chemistry', c: '#7a9a9a', ab: 'SC', kw: 40, cost: { plate: 6, lead_sheet: 2, motor: 1 }, d: 'Sprays flue gas with a slurry or solution that soaks up the acid gas.' },
  stack: { n: 'Chimney Stack', kind: 'stack', w: 1, h: 1, cat: 'Chemistry', c: '#8a7a70', ab: 'ST', cost: { brick: 12 }, d: 'Machines touching it vent high up. Their fumes spread over a wide area instead of smothering the ground nearby.' },
  brick_wall: { n: 'Brick Wall', kind: 'wall', w: 1, h: 1, cat: 'Defence', c: '#a8603a', cost: { brick: 2 }, makes: 2, hp: 400, d: 'Fired brick in lime mortar. Crawlers have to chew through it.' },
  concrete_wall: { n: 'Concrete Wall', kind: 'wall', w: 1, h: 1, cat: 'Defence', c: '#a8a8a2', cost: { concrete: 2 }, makes: 2, hp: 1200, d: 'Three times tougher than brick. Their acid etches concrete only slowly.' },
  armour_wall: { n: 'Armour Wall', kind: 'wall', w: 1, h: 1, cat: 'Defence', c: '#6a7888', cost: { v_steel: 2 }, makes: 2, hp: 3000, d: 'Vanadium steel plate on a concrete footing. It takes crawlers two and a half times longer to chew through than concrete.' },
  pvc_pipe: { n: 'PVC Pipe', kind: 'pipe', w: 1, h: 1, cat: 'Logistics', c: '#d8dcd4', cost: { pvc: 1 }, makes: 2, d: 'DN50, rated 16 bar. Immune to acid, chlorine, brine and caustic, but rigid PVC softens at 60°C and shatters when overpressured. Keep steam and hot liquor out of it.', P: { mat: 'Rigid PVC', dn: 50, v: 100, g: 200, q: 120, bar: 16, tmax: 60, duct: 0, cw: 25, ua: 0.15, res: 'acid cl alk', plastic: 1 } },
  pe_pipe: { n: 'HDPE Pipe', kind: 'pipe', w: 1, h: 1, cat: 'Logistics', c: '#2a2a2a', cost: { polyethylene: 2 }, makes: 2, d: 'DN100, rated only 8 bar. Black polyethylene that stretches a long way before it splits, and nothing but hot nitric acid touches it, fluorides included. It sags above 60°C.', P: { mat: 'High-density polyethylene', dn: 100, v: 250, g: 800, q: 400, bar: 8, tmax: 60, duct: 5, cw: 25, ua: 0.15, res: 'acid cl alk hf', plastic: 1 } },
  turret: { n: 'Gun Turret', kind: 'turret', w: 2, h: 2, cat: 'Defence', c: '#5a6a5a', ab: 'GT', cost: { plate: 6, casting: 6, motor: 1 }, hp: 500, d: 'Fires lead shot at crawlers within 10 tiles. Load cartridges by hand, from a chest or off a belt.' },
  hive: { n: 'Crawler Hive', kind: 'hive', w: 2, h: 2, c: '#6a4a5a', hp: 1000, d: 'A mound of chewed rock and mucus. Sulfur-oxidising bacteria in the crawlers\' guts live on SO₂ and the creatures follow the smog to its source.' },
  haber: { n: 'Ammonia Converter', kind: 'machine', w: 3, h: 3, cat: 'Chemistry', c: '#5a8aa8', ab: 'HB', kw: 250, lock: 'haber', cost: { plate: 14, motor: 3 }, d: 'Haber-Bosch loop: nitrogen from the air and hydrogen are squeezed to 200 bar over an iron catalyst at 450°C. Compressors take most of the power.' },
  ostwald: { n: 'Ostwald Burner', kind: 'machine', w: 2, h: 2, cat: 'Chemistry', c: '#b0a060', ab: 'OB', cost: { plate: 6, pt_gauze: 1, brick: 4 }, d: 'Ammonia and air flash through red-hot platinum gauze. The reaction keeps the gauze glowing, so it needs no fuel.' },
  filler: { n: 'Cylinder Filler', kind: 'machine', w: 2, h: 2, cat: 'Defence', c: '#6a8a6a', ab: 'CF', kw: 20, cost: { plate: 4, casting: 2, motor: 1 }, d: 'Compresses and liquefies gas into steel cylinders.' },
  projector: { n: 'Livens Projector', kind: 'projector', w: 2, h: 2, cat: 'Defence', c: '#5a5a4a', ab: 'LP', hp: 400, cost: { plate: 8, casting: 4 }, d: 'A battery of buried mortar tubes that lob gas cylinders or explosive drums at hives up to 28 tiles away. Each shot burns one blasting powder charge.' },
  ruin: { n: 'Abandoned Works', kind: 'ruin', w: 3, h: 3, c: '#6a6058', ab: 'AW', d: 'A chemical works from before the crawlers came. The roof is in, but the stores and the lab books may have survived.' },
  retort: { n: 'Hunter Retort', kind: 'machine', w: 2, h: 2, cat: 'Chemistry', c: '#8a8a9a', ab: 'HR', kw: 80, cost: { plate: 10, brick: 6 }, d: 'Sealed steel pot where molten sodium strips chlorine from TiCl₄.' },
  still: { n: 'Distillation Column', kind: 'machine', w: 2, h: 2, cat: 'Chemistry', c: '#8a7a5a', ab: 'DC', kw: 40, cost: { plate: 8, brick: 4 }, d: 'A tall column of bubble-cap trays. Steam heats the bottom and each tray holds a liquid that boils a little cooler than the one below.' },
  solvay: { n: 'Solvay Tower', kind: 'machine', w: 2, h: 2, cat: 'Chemistry', c: '#7a9ab0', ab: 'SV', kw: 60, cost: { plate: 10, casting: 6, motor: 1 }, d: 'Ammoniated brine trickles down past perforated plates while carbon dioxide bubbles up. Sodium bicarbonate is the least soluble salt in the mix, so it falls out.' },
  glass_tank: { n: 'Glass Tank Furnace', kind: 'machine', w: 3, h: 3, cat: 'Smelting', c: '#a87a5a', ab: 'GF', kw: 40, cost: { brick: 16, plate: 4 }, d: 'A pool of molten glass at 1500°C. Batch goes in one end and clear glass is drawn off the other.' },
  nitrator: { n: 'Nitrator', kind: 'machine', w: 2, h: 2, cat: 'Chemistry', c: '#a89a5a', ab: 'NI', kw: 60, lock: 'tnt', cost: { plate: 8, glass: 4, motor: 1 }, d: 'Stirred, water-cooled cast iron pot. Mixed nitric and sulfuric acid add one nitro group at a time; let it run hot and the batch can fume off or detonate.' },
  howitzer: { n: 'Field Howitzer', kind: 'gun', w: 2, h: 2, cat: 'Defence', c: '#5a6248', ab: 'HW', hp: 600, lock: 'shell', cost: { plate: 12, casting: 8, motor: 2 }, d: 'A 4.5-inch howitzer that lobs high-explosive shells at hives up to 44 tiles away. Feed it shells by hand, from a chest or off a belt.' },
  producer: { n: 'Gas Producer', kind: 'machine', w: 2, h: 2, cat: 'Chemistry', c: '#6a5a4a', ab: 'GP', cost: { brick: 10, plate: 4 }, d: 'A brick-lined shaft of glowing coke. Gas blown up through the bed leaves as carbon monoxide.' },
  pumpjack: { n: 'Pumpjack', kind: 'machine', w: 2, h: 2, cat: 'Mining', c: '#6a5a3a', ab: 'PJ', kw: 40, well: true, cost: { plate: 8, casting: 6, motor: 2 }, d: 'A nodding beam pump on top of a drilled well. It lifts crude from the rock below an oil seep, and the field slowly runs dry.' },
  cdu: { n: 'Crude Distillation Unit', kind: 'machine', w: 3, h: 3, cat: 'Chemistry', c: '#7a6a4a', ab: 'CD', kw: 60, cost: { plate: 16, brick: 8, motor: 2 }, d: 'A furnace heats crude to 370°C and flashes it into a 40-tray column. Light cuts rise to the top, heavy ones drain off lower down, and bitumen is left at the bottom.' },
  cracker: { n: 'Tube Furnace', kind: 'machine', w: 3, h: 3, cat: 'Chemistry', c: '#a8583a', ab: 'TF', kw: 30, cost: { brick: 16, steel: 6, motor: 1 }, d: 'Alloy tubes hung in a gas-fired firebox. Steam crackers, steam reformers and EDC crackers are all this furnace with a different feed and catalyst.' },
  reactor: { n: 'Pressure Reactor', kind: 'machine', w: 2, h: 2, cat: 'Chemistry', c: '#6a8a9a', ab: 'PX', kw: 60, cost: { plate: 10, glass: 2, motor: 2 }, d: 'A stirred, jacketed pressure vessel. Polymerises ethylene and vinyl chloride, and chlorinates ethylene to EDC.' },
  granulator: { n: 'Granulator Drum', kind: 'machine', w: 2, h: 2, cat: 'Chemistry', c: '#8a9a5a', ab: 'GR', kw: 50, cost: { plate: 8, brick: 4, motor: 2 }, d: 'A slowly turning, gently sloped drum. Acid and ammonia sprayed onto a rolling bed of powder react and build up layer by layer into hard, round granules.' },
  claus: { n: 'Claus Unit', kind: 'machine', w: 2, h: 2, cat: 'Chemistry', c: '#b8a040', ab: 'CU', kw: 20, cost: { brick: 10, plate: 6, steel_pipe: 4 }, d: 'A burner and a train of alumina catalyst beds that turn hydrogen sulfide into liquid sulfur. The reaction heat raises steam in a waste-heat boiler.' },
  diesel_gen: { n: 'Diesel Generator', kind: 'machine', w: 2, h: 2, cat: 'Power', c: '#5a6a5a', ab: 'DG', gen: 600, cost: { steel: 8, casting: 6, motor: 4, wire: 10 }, d: 'A compression-ignition engine on an alternator. Up to 600 kW, and it only burns fuel for the power drawn. Raw gas oil works but sends its sulfur up the exhaust as SO₂.' },
  depot: { n: 'Rail Depot', kind: 'chest', w: 3, h: 3, cat: 'Logistics', c: '#5a6a7a', ab: 'RD', cost: { plate: 10, casting: 10, brick: 10 }, d: 'A goods siding where customers\' wagons are loaded. Belts, chests and machines touching it fill the open orders. Every finished order pays in parts, and every third brings a lab notebook from the buyer.' },
  phos_rx: { n: 'Phosgene Reactor', kind: 'machine', w: 2, h: 2, cat: 'Chemistry', c: '#8a8a6a', ab: 'PH', kw: 30, lock: 'phosgene', cost: { plate: 8, glass: 4, motor: 1 }, d: 'Water-jacketed tubes packed with activated carbon. Carbon monoxide and chlorine combine on the carbon surface at about 200°C.' },
};

const RECIPES = [
  { id: 'crush_iron', b: 'crusher', t: 1.5, i: { iron_ore: 1 }, o: { crushed_iron: 1 } },
  { id: 'crush_copper', b: 'crusher', t: 1.5, i: { copper_ore: 1 }, o: { crushed_copper: 1 } },
  { id: 'crush_pbzn', b: 'crusher', t: 1.5, i: { pbzn_ore: 1 }, o: { crushed_pbzn: 1 } },
  { id: 'crush_lime', b: 'crusher', t: 1, i: { limestone: 1 }, o: { crushed_lime: 1 } },
  { id: 'grind_iron', b: 'mill', t: 2, i: { crushed_iron: 1 }, fi: { water: 10 }, o: { ground_iron: 1 }, note: 'Grinding frees each mineral grain so it can be separated.' },
  { id: 'grind_copper', b: 'mill', t: 2, i: { crushed_copper: 1 }, fi: { water: 10 }, o: { ground_copper: 1 } },
  { id: 'grind_pbzn', b: 'mill', t: 2, i: { crushed_pbzn: 1 }, fi: { water: 10 }, o: { ground_pbzn: 1 } },
  { id: 'mag_iron', b: 'magsep', t: 2, i: { ground_iron: 2 }, o: { iron_conc: 1, tailings: 1 }, note: 'Magnetite is strongly magnetic; hematite needs a high-intensity field. Quartz is not magnetic.' },
  { id: 'float_copper', b: 'flotation', t: 3, i: { ground_copper: 3 }, fi: { water: 20 }, o: { copper_conc: 1, pyrite_conc: 1, tailings: 1 }, note: 'Xanthate collectors coat chalcopyrite so it sticks to air bubbles. Lime raises the pH so pyrite floats later, in its own froth.' },
  { id: 'float_lead', b: 'flotation', t: 3, i: { ground_pbzn: 3 }, fi: { water: 20 }, o: { galena_conc: 1, zinc_rougher: 2 }, note: 'Sphalerite is held down (depressed) so only galena floats first.' },
  { id: 'float_zinc', b: 'flotation', t: 3, i: { zinc_rougher: 2 }, fi: { water: 15 }, o: { sphalerite_conc: 1, tailings: 1 }, note: 'Copper sulfate activates the sphalerite surface so it floats in the second stage.' },
  { id: 'coke', b: 'coke_oven', t: 6, i: { coal: 2 }, o: { coke: 1 }, eq: 'Coal → C + volatiles', note: 'Heated to about 1000°C without air, coal loses tar and gas and leaves strong, porous coke.' },
  { id: 'lime', b: 'kiln', t: 4, i: { limestone: 2, coal: 1 }, o: { quicklime: 2 }, fo: { co2: 20 }, eq: 'CaCO₃ → CaO + CO₂', note: 'Calcination at about 900°C. The coal is fuel.' },
  { id: 'roast_copper', b: 'roaster', t: 3, i: { copper_conc: 1 }, o: { copper_calcine: 1 }, fo: { so2: 20 }, eq: '2CuFeS₂ + 4O₂ → Cu₂S + 2FeO + 3SO₂', note: 'Burning sulfide releases its own heat, so no fuel is needed.' },
  { id: 'roast_galena', b: 'roaster', t: 3, i: { galena_conc: 1 }, o: { lead_oxide: 1 }, fo: { so2: 15 }, eq: '2PbS + 3O₂ → 2PbO + 2SO₂' },
  { id: 'roast_zinc', b: 'roaster', t: 3, i: { sphalerite_conc: 1 }, o: { zinc_calcine: 1 }, fo: { so2: 15 }, eq: '2ZnS + 3O₂ → 2ZnO + 2SO₂' },
  { id: 'pig_iron', b: 'blast', t: 4, i: { iron_conc: 2, coke: 1, crushed_lime: 1 }, o: { pig_iron: 2, slag: 1 }, fo: { co2: 30 }, eq: 'Fe₂O₃ + 3CO → 2Fe + 3CO₂ ; CaCO₃ + SiO₂ → CaSiO₃ + CO₂', note: 'Coke burns to CO, which strips oxygen from the ore. Limestone flux turns leftover quartz into runny slag.' },
  { id: 'lead_bullion', b: 'blast', t: 4, i: { lead_oxide: 2, coke: 1 }, o: { lead: 2 }, fo: { co2: 15 }, eq: 'PbO + CO → Pb + CO₂' },
  { id: 'steel', b: 'converter', t: 4, i: { pig_iron: 3 }, o: { steel: 2, slag: 1 }, fo: { co2: 15 }, eq: 'C + O₂ → CO₂ (Bessemer process)', note: 'Air blown through molten pig iron burns the carbon out. The reaction is hot enough to keep the iron molten by itself.' },
  { id: 'blister', b: 'converter', t: 4, i: { copper_matte: 2 }, o: { blister_copper: 1 }, fo: { so2: 25 }, eq: 'Cu₂S + O₂ → 2Cu + SO₂' },
  { id: 'matte', b: 'smelter', t: 4, i: { copper_calcine: 2, sand: 1 }, o: { copper_matte: 1, slag: 1 }, eq: '2FeO + SiO₂ → Fe₂SiO₄ (slag)', note: 'Silica flux pulls the iron into a fayalite slag that floats on the heavier copper matte.' },
  { id: 'acid', b: 'acid_plant', t: 2, fi: { so2: 30, water: 10 }, fo: { acid: 20 }, eq: '2SO₂ + O₂ → 2SO₃ (V₂O₅) ; SO₃ + H₂O → H₂SO₄', cat: 'v_cat', boost: 1.5, life: 400, note: 'Without a catalyst bed this runs as a lead chamber, where nitrogen oxides carry the oxygen slowly. Load V₂O₅ rings for the Contact process at up to 2.5× speed. Lead lining resists the acid.' },
  { id: 'leach_zinc', b: 'leach', t: 3, i: { zinc_calcine: 1 }, fi: { acid: 20 }, fo: { znso4: 20 }, eq: 'ZnO + H₂SO₄ → ZnSO₄ + H₂O' },
  { id: 'refine_copper', b: 'electro', t: 4, i: { blister_copper: 1 }, fi: { acid: 5 }, o: { copper_cathode: 1 }, ch: { anode_slime: 0.15 }, eq: 'Cu (anode) → Cu²⁺ → Cu (cathode)', note: 'Impure anodes dissolve and pure copper plates onto the cathode. Gold and silver fall to the bottom as anode slime.' },
  { id: 'winning_zinc', b: 'electro', t: 4, fi: { znso4: 20 }, o: { zinc: 1 }, fo: { acid: 15 }, bleed: ['acid'], eq: '2ZnSO₄ + 2H₂O → 2Zn + 2H₂SO₄ + O₂', note: 'Electrowinning gives the acid back, so it loops to the leach tank. Spent acid that has nowhere to go is bled off.' },
  { id: 'steam_coal', n: 'Steam (coal)', b: 'boiler', t: 2, i: { coal: 1 }, fi: { water: 60 }, fo: { steam: 60 }, eq: 'C + O₂ → CO₂ (heat boils water)' },
  { id: 'steam_coke', n: 'Steam (coke)', b: 'boiler', t: 3, i: { coke: 1 }, fi: { water: 90 }, fo: { steam: 90 } },
  { id: 'casting', b: 'workshop', t: 1, i: { pig_iron: 1 }, o: { casting: 1 } },
  { id: 'plate', b: 'workshop', t: 1, i: { steel: 1 }, o: { plate: 1 } },
  { id: 'wire', b: 'workshop', t: 0.5, i: { copper_cathode: 1 }, o: { wire: 2 } },
  { id: 'motor', b: 'workshop', t: 3, i: { casting: 1, plate: 1, wire: 3 }, o: { motor: 1 } },
  { id: 'brick', b: 'workshop', t: 2, i: { sand: 2, quicklime: 1 }, o: { brick: 1 } },
  { id: 'lead_sheet', b: 'workshop', t: 1, i: { lead: 1 }, o: { lead_sheet: 1 } },
  { id: 'brass', b: 'workshop', t: 2, i: { copper_cathode: 2, zinc: 1 }, o: { brass: 3 } },
  { id: 'crush_salt', b: 'crusher', t: 1, i: { rock_salt: 1 }, o: { salt: 1 } },
  { id: 'brine', b: 'leach', t: 2, i: { salt: 2 }, fi: { water: 20 }, fo: { brine: 20 }, eq: 'NaCl(s) → Na⁺ + Cl⁻ (aq)' },
  { id: 'chloralkali', n: 'Chlor-alkali', b: 'electro', t: 3, fi: { brine: 20 }, fo: { cl2: 10, naoh: 10, h2: 10 }, bleed: ['h2'], eq: '2NaCl + 2H₂O → Cl₂ + H₂ + 2NaOH', note: 'Chlor-alkali process. A membrane keeps the chlorine at the anode apart from the caustic at the cathode. Hydrogen with nowhere to go is vented.' },
  { id: 'downs', n: 'Sodium (Downs cell)', b: 'electro', t: 4, i: { salt: 2 }, o: { sodium: 2 }, fo: { cl2: 10 }, eq: '2NaCl (molten) → 2Na + Cl₂', note: 'Downs cell: molten salt at 600°C. Sodium floats up at the cathode, chlorine bubbles off the graphite anode.' },
  { id: 'steam_h2', n: 'Steam (hydrogen)', b: 'boiler', t: 2, fi: { h2: 30, water: 60 }, fo: { steam: 60 }, eq: '2H₂ + O₂ → 2H₂O (heat boils water)', note: 'Burning by-product hydrogen beats venting it.' },
  { id: 'crush_bauxite', b: 'crusher', t: 1.5, i: { bauxite: 1 }, o: { crushed_bauxite: 1 } },
  { id: 'digest', n: 'Aluminate Liquor', b: 'digester', t: 3, i: { crushed_bauxite: 2 }, fi: { naoh: 20, steam: 10 }, fo: { liquor: 20 }, o: { red_mud: 1 }, eq: 'Al(OH)₃ + NaOH → NaAl(OH)₄', note: 'Bayer process. Iron and titanium oxides do not dissolve and settle as red mud.' },
  { id: 'precipitate', b: 'precipitator', t: 3, fi: { liquor: 20 }, o: { al_hydroxide: 1 }, ch: { gallium: 0.05 }, fo: { naoh: 15 }, bleed: ['naoh'], eq: 'NaAl(OH)₄ → Al(OH)₃ + NaOH', note: 'Cooling the liquor reverses the digestion. The caustic returns to the digester; gallium trails aluminium and is recovered from the liquor.' },
  { id: 'calcine', b: 'kiln', t: 3, i: { al_hydroxide: 2, coal: 1 }, o: { alumina: 1 }, fo: { co2: 15 }, eq: '2Al(OH)₃ → Al₂O₃ + 3H₂O', note: 'Calcination at 1100°C drives off the water.' },
  { id: 'anode', b: 'coke_oven', t: 4, i: { coke: 2 }, o: { anode: 1 }, note: 'Coke is bound with pitch, pressed and baked into blocks.' },
  { id: 'aluminium', b: 'pot', t: 4, i: { alumina: 2, anode: 1 }, o: { aluminium: 2 }, fo: { co2: 10 }, eq: '2Al₂O₃ + 3C → 4Al + 3CO₂', note: 'Hall-Héroult process at 960°C. Alumina dissolves in molten cryolite Na₃AlF₆; the carbon anode burns away as CO₂. Real smelters use about 14 kWh per kg.' },
  { id: 'spiral', b: 'spiral', t: 2, i: { mineral_sand: 3 }, fi: { water: 15 }, o: { heavy_conc: 1, sand: 2 }, note: 'Heavy minerals (density 4-5) sink to the inside of the spiral; quartz (2.65) washes to the outside.' },
  { id: 'mag_heavy', b: 'magsep', t: 2, i: { heavy_conc: 2 }, o: { ilmenite: 1, nonmag: 1 }, note: 'Ilmenite holds iron, so a strong magnet lifts it away.' },
  { id: 'esep', b: 'esep', t: 2, i: { nonmag: 2 }, o: { rutile: 1, zircon: 1 }, ch: { monazite: 0.2 }, note: 'Rutile is a semiconductor and loses its charge on the earthed roll, so it flies off. Zircon and monazite are insulators and stick.' },
  { id: 'ti_slag', b: 'arc', t: 4, i: { ilmenite: 2, coke: 1 }, o: { ti_slag: 1, v_pig: 1 }, fo: { co2: 10 }, eq: 'FeTiO₃ + C → Fe + TiO₂ + CO', note: 'Smelting removes the iron as pig iron and concentrates titanium in the slag. The vanadium in the ore goes with the iron.' },
  { id: 'chlorinate', n: 'TiCl₄ from Rutile', b: 'chlorinator', t: 3, i: { rutile: 1, coke: 1 }, fi: { cl2: 20 }, fo: { ticl4: 10, co2: 5 }, bleed: ['co2'], eq: 'TiO₂ + 2Cl₂ + C → TiCl₄ + CO₂', note: 'At 1000°C titanium leaves as a gas and is condensed. Most other oxides stay behind.' },
  { id: 'chlorinate_slag', n: 'TiCl₄ from Slag', b: 'chlorinator', t: 3, i: { ti_slag: 1, coke: 1 }, fi: { cl2: 20 }, fo: { ticl4: 8, co2: 5 }, bleed: ['co2'], eq: 'TiO₂ + 2Cl₂ + C → TiCl₄ + CO₂', note: 'Slag has more impurities, so less TiCl₄ per batch.' },
  { id: 'hunter', b: 'retort', t: 5, i: { sodium: 4 }, fi: { ticl4: 10 }, o: { titanium: 1, salt: 4 }, eq: 'TiCl₄ + 4Na → Ti + 4NaCl', note: 'Hunter process. The salt goes back to the Downs cell, so the sodium and chlorine loop closes.' },
  { id: 'zircon_brick', n: 'Zircon Brick', b: 'workshop', t: 2, i: { zircon: 1 }, o: { brick: 2 }, note: 'Zircon bricks outlast silica in the hottest furnaces.' },
  { id: 'roast_pyrite', b: 'roaster', t: 3, i: { pyrite_conc: 1 }, o: { pyrite_cinder: 1 }, fo: { so2: 25 }, eq: '4FeS₂ + 11O₂ → 2Fe₂O₃ + 8SO₂', note: 'Pyrite was the main source of sulfuric acid for a century.' },
  { id: 'pig_cinder', n: 'Pig Iron from Cinder', b: 'blast', t: 4, i: { pyrite_cinder: 2, coke: 1, crushed_lime: 1 }, o: { pig_iron: 2, slag: 1 }, fo: { co2: 30 }, eq: 'Fe₂O₃ + 3CO → 2Fe + 3CO₂' },
  { id: 'roast_slime', b: 'roaster', t: 4, i: { anode_slime: 2 }, o: { dore: 1 }, ch: { selenium: 0.5 }, fo: { so2: 5 }, eq: 'Se + O₂ → SeO₂ (volatilised and scrubbed)', note: 'Roasting drives off selenium; the rest is melted into a silver-gold doré.' },
  { id: 'affination', b: 'leach', t: 4, i: { dore: 2 }, fi: { acid: 10 }, o: { silver: 1 }, ch: { gold: 0.4 }, fo: { so2: 5 }, eq: '2Ag + 2H₂SO₄ → Ag₂SO₄ + SO₂ + 2H₂O', note: 'Hot concentrated acid dissolves the silver (then recovered on copper) and leaves the gold untouched.' },
  { id: 'fgd', n: 'Flue Gas Desulfurisation', b: 'scrubber', t: 3, i: { crushed_lime: 1 }, fi: { so2: 20, water: 10 }, o: { gypsum: 1 }, fo: { co2: 5 }, bleed: ['co2'], eq: '2SO₂ + 2CaCO₃ + O₂ + 4H₂O → 2CaSO₄·2H₂O + 2CO₂', note: 'Wet limestone scrubbing. Air blown into the slurry oxidises sulfite to gypsum, which sells as plasterboard and cement.' },
  { id: 'bleach', b: 'scrubber', t: 2, fi: { cl2: 20, naoh: 20 }, o: { bleach: 1 }, eq: 'Cl₂ + 2NaOH → NaOCl + NaCl + H₂O', note: 'Caustic soaks up chlorine. Every chlor-alkali plant has one of these as an emergency absorber.' },
  { id: 'clinker', b: 'kiln', t: 5, i: { crushed_lime: 3, sand: 1, coal: 1 }, o: { clinker: 2 }, fo: { co2: 30 }, eq: '3CaCO₃ + SiO₂ → Ca₃SiO₅ + 3CO₂', note: 'Cement kilns are among the largest CO₂ sources on Earth: the limestone itself gives off CO₂, before any fuel is burned.' },
  { id: 'cement', b: 'mill', t: 2, i: { clinker: 2, gypsum: 1 }, o: { cement: 3 }, note: 'About 5% gypsum controls the reaction of tricalcium aluminate so the cement stays workable.' },
  { id: 'slag_cement', n: 'Slag Cement', b: 'mill', t: 2, i: { clinker: 1, slag: 2, gypsum: 1 }, o: { cement: 3 }, note: 'Ground blast furnace slag is a latent cement. Blending it in halves the clinker, and so the CO₂.' },
  { id: 'concrete', b: 'workshop', t: 2, i: { cement: 1, sand: 3 }, o: { concrete: 2 }, eq: 'Ca₃SiO₅ + H₂O → C-S-H gel + Ca(OH)₂', note: 'Water is mixed in and the blocks are cured for a few days.' },
  { id: 'crush_caliche', b: 'crusher', t: 1, i: { caliche: 1 }, o: { crushed_caliche: 1 } },
  { id: 'saltpetre', n: 'Sodium Nitrate', b: 'leach', t: 3, i: { crushed_caliche: 2 }, fi: { steam: 10, water: 10 }, o: { sodium_nitrate: 1, salt: 1 }, eq: 'NaNO₃ dissolves far more in hot water than NaCl', note: 'Shanks process, used in the Atacama from 1876. Hot leach liquor dissolves the nitrate; on cooling the nitrate crystallises out while most of the salt stays behind.' },
  { id: 'pyrite_sulfur', n: 'Sulfur from Pyrite', b: 'kiln', t: 4, i: { pyrite_conc: 2, coal: 1 }, o: { sulfur: 1, pyrite_cinder: 1 }, fo: { so2: 10 }, eq: 'FeS₂ → FeS + S ; 4FeS + 7O₂ → 2Fe₂O₃ + 4SO₂', note: 'Heating pyrite without much air drives off one sulfur atom as vapour, which condenses yellow. The rest burns off as SO₂.' },
  { id: 'black_powder', b: 'mill', t: 3, i: { sodium_nitrate: 3, sulfur: 1, coal: 1 }, o: { black_powder: 5 }, eq: '2NaNO₃ + S + 3C → Na₂SO₄ + N₂ + 3CO₂ (roughly)', note: 'DuPont \'B\' blasting powder swapped expensive potassium saltpetre for Chilean sodium nitrate. It soaks up damp, so it was used where that did not matter.' },
  { id: 'cylinder', b: 'workshop', t: 2, i: { plate: 2 }, o: { cylinder: 1 }, note: 'Pierced and drawn from a steel billet, then hydraulically tested.' },
  { id: 'fill_cl2', n: 'Fill Chlorine', b: 'filler', t: 2, i: { cylinder: 1 }, fi: { cl2: 40 }, o: { cl2_cyl: 1 }, note: 'Chlorine liquefies at 7 bar at room temperature. At Ypres in April 1915, 5,730 such cylinders were opened at once.' },
  { id: 'fill_nh3', n: 'Fill Ammonia', b: 'filler', t: 2, i: { cylinder: 1 }, fi: { nh3: 40 }, o: { nh3_cyl: 1 }, note: 'Ammonia liquefies at about 9 bar. Refrigeration plants have stored it this way since the 1870s.' },
  { id: 'haber', n: 'Ammonia', b: 'haber', t: 3, lock: 1, fi: { h2: 30 }, fo: { nh3: 20 }, cat: 'fe_cat', boost: 1, life: 500, eq: 'N₂ + 3H₂ ⇌ 2NH₃', note: 'Haber-Bosch process, 1913. A fresh charge of fused iron catalyst doubles the rate. Only about 15% converts per pass, so the gas loops through the catalyst again and again. It now feeds half the people on Earth through fertiliser.' },
  { id: 'ostwald', n: 'Nitric Acid', b: 'ostwald', t: 3, lock: 1, fi: { nh3: 10, water: 10 }, fo: { hno3: 10 }, eq: '4NH₃ + 5O₂ → 4NO + 6H₂O (Pt) ; 2NO + O₂ → 2NO₂ ; 3NO₂ + H₂O → 2HNO₃ + NO', note: 'Ostwald process. The gauze slowly loses platinum to the gas stream.' },
  { id: 'nitric_retort', n: 'Nitric Acid (saltpetre)', b: 'retort', t: 4, i: { sodium_nitrate: 2 }, fi: { acid: 10 }, fo: { hno3: 6 }, eq: 'NaNO₃ + H₂SO₄ → NaHSO₄ + HNO₃', note: 'Glauber\'s route, used for 250 years: distil saltpetre with sulfuric acid. Slow and costly next to burning ammonia.' },
  { id: 'amm_nitrate', b: 'leach', t: 2, lock: 1, fi: { nh3: 10, hno3: 10 }, o: { amm_nitrate: 2 }, eq: 'NH₃ + HNO₃ → NH₄NO₃', note: 'The neutralisation boils off water by its own heat. The melt is sprayed down a tower and freezes into prills.' },
  { id: 'ammonal', b: 'mill', t: 3, lock: 1, i: { amm_nitrate: 4, aluminium: 1, coal: 1 }, o: { ammonal: 4 }, eq: '3NH₄NO₃ + 2Al → 3N₂ + 6H₂O + Al₂O₃', note: 'Aluminium burns with the oxygen the nitrate gives up. It was the British army\'s mining explosive under the Messines ridge in 1917.' },
  { id: 'he_drum', n: 'Ammonal Drum', b: 'workshop', t: 3, lock: 1, i: { cylinder: 1, ammonal: 4, black_powder: 1 }, o: { he_drum: 1 } },
  { id: 'nh3_scrub', n: 'Ammonia Scrubbing', b: 'scrubber', t: 2, lock: 1, fi: { so2: 20, nh3: 10, water: 10 }, o: { amm_sulfate: 2 }, eq: 'SO₂ + 2NH₃ + H₂O + ½O₂ → (NH₄)₂SO₄', note: 'Walther process. Unlike limestone it gives off no CO₂, and the product sells as fertiliser.' },
  { id: 'coke_byp', n: 'Coke + By-products', b: 'coke_oven', t: 6, i: { coal: 2 }, o: { coke: 1 }, fo: { tar: 10, coalgas: 20 }, eq: 'Coal → C + tar + H₂ + CH₄ + CO', note: 'Koppers by-product oven. Instead of burning off the volatiles, the gas is cooled, the tar condenses out and the gas is piped away. Without a tar pipe the oven stops; unpiped gas is flared.' },
  { id: 'steam_gas', n: 'Steam (coke oven gas)', b: 'boiler', t: 2, fi: { coalgas: 30, water: 60 }, fo: { steam: 60 }, eq: '2H₂ + O₂ → 2H₂O ; CH₄ + 2O₂ → CO₂ + 2H₂O', note: 'Steelworks burned their own oven gas under the boilers.' },
  { id: 'tar_dist', n: 'Tar Distillation', b: 'still', t: 5, fi: { tar: 20, steam: 10 }, fo: { toluene: 6 }, o: { pitch: 1 }, eq: 'Coal tar → light oil (benzene, toluene) + carbolic oil + creosote + pitch', note: 'About a third of the tar boils off; the black pitch stays behind.' },
  { id: 'anode_pitch', n: 'Carbon Anode (pitch)', b: 'coke_oven', t: 4, i: { coke: 2, pitch: 1 }, o: { anode: 3 }, eq: 'Coke + pitch → baked carbon', note: 'Pitch soaks into the coke grains and turns to carbon when baked, so far more of the coke ends up as anode.' },
  { id: 'solvay', n: 'Solvay Process', b: 'solvay', t: 3, fi: { brine: 20, nh3: 10, co2: 20 }, o: { nahco3: 2 }, fo: { nh4cl: 20 }, eq: 'NaCl + NH₃ + CO₂ + H₂O → NaHCO₃↓ + NH₄Cl', note: 'Ernest Solvay, 1861. It replaced the filthy Leblanc process, whose hydrochloric acid fumes killed fields downwind. The ammonia is too costly to lose, so it is boiled back out of the liquor.' },
  { id: 'nh3_still', n: 'Ammonia Recovery', b: 'still', t: 3, i: { quicklime: 1 }, fi: { nh4cl: 20, steam: 10 }, fo: { nh3: 9 }, o: { cacl2: 1 }, eq: '2NH₄Cl + CaO → 2NH₃ + CaCl₂ + H₂O', note: 'Lime liberates the ammonia, which steam strips out for the tower. About 10% is lost each turn.' },
  { id: 'soda_ash', n: 'Soda Ash', b: 'kiln', t: 3, i: { nahco3: 2 }, o: { soda_ash: 1 }, fo: { co2: 10 }, eq: '2NaHCO₃ → Na₂CO₃ + CO₂ + H₂O', note: 'Half the carbon dioxide comes back out and goes round to the tower again.' },
  { id: 'causticise', n: 'Caustic Soda (lime-soda)', b: 'leach', t: 3, i: { soda_ash: 1, quicklime: 1 }, fi: { water: 20 }, fo: { naoh: 20 }, o: { crushed_lime: 1 }, eq: 'Na₂CO₃ + CaO + H₂O → 2NaOH + CaCO₃↓', note: 'How caustic soda was made before chlor-alkali cells. No power and no chlorine, and the chalk mud goes back to the kiln.' },
  { id: 'glass', b: 'glass_tank', t: 4, i: { sand: 3, soda_ash: 1, crushed_lime: 1 }, o: { glass: 3 }, fo: { co2: 10 }, eq: 'Na₂CO₃ + CaCO₃ + 6SiO₂ → Na₂O·CaO·6SiO₂ + 2CO₂', note: 'Soda lowers the melting point of silica from 1700°C to about 1000°C; lime makes the glass stop dissolving in water.' },
  { id: 'tnt', n: 'TNT', b: 'nitrator', t: 4, lock: 1, fi: { toluene: 10, hno3: 15, acid: 10 }, o: { tnt: 2 }, eq: 'C₇H₈ + 3HNO₃ → C₇H₅N₃O₆ + 3H₂O (H₂SO₄)', note: 'Sulfuric acid soaks up the water and makes the nitronium ion NO₂⁺ that does the work. Three stages, each hotter and with stronger acid.' },
  { id: 'shell', n: 'HE Shell', b: 'workshop', t: 3, lock: 1, i: { plate: 1, brass: 1, tnt: 1, black_powder: 1 }, o: { shell: 2 }, note: 'TNT melts at 80°C, so it is simply poured into the shell body like wax.' },
  { id: 'boudouard', n: 'Producer Gas (CO₂)', b: 'producer', t: 3, i: { coke: 1 }, fi: { co2: 20 }, fo: { co: 40 }, eq: 'C + CO₂ → 2CO', note: 'The Boudouard reaction only runs above about 900°C, where the equilibrium swings almost entirely to CO. It turns waste flue gas back into fuel.' },
  { id: 'water_gas', n: 'Water Gas', b: 'producer', t: 3, i: { coke: 1 }, fi: { steam: 20 }, fo: { co: 20, h2: 20 }, eq: 'C + H₂O → CO + H₂', note: 'Blow steam through white-hot coke and it splits into CO and hydrogen. The reaction cools the bed, so real producers alternated steam runs with air blows.' },
  { id: 'activate', n: 'Activated Carbon', b: 'producer', t: 5, i: { coke: 3 }, fi: { steam: 20 }, o: { carbon: 1 }, fo: { co: 10 }, eq: 'C + H₂O → CO + H₂ (partial)', note: 'Steam burns away part of the carbon from the inside, opening a maze of pores. The same carbon went into gas mask canisters in 1915.' },
  { id: 'phosgene', n: 'Phosgene', b: 'phos_rx', t: 4, lock: 1, i: { carbon: 1 }, fi: { co: 40, cl2: 40 }, fo: { phosgene: 40 }, eq: 'CO + Cl₂ → COCl₂ (activated carbon)', note: 'The carbon is a catalyst, but it slowly fouls and is replaced. Still made by the million tonnes today to make polycarbonate and polyurethane.' },
  { id: 'fill_phos', n: 'Fill Phosgene', b: 'filler', t: 2, lock: 1, i: { cylinder: 1 }, fi: { phosgene: 40 }, o: { phos_cyl: 1 }, note: 'Phosgene caused most of the gas deaths of the First World War. It was mixed with chlorine as White Star so the cloud could be seen and drift heavily.' },
  { id: 'crush_phos', b: 'crusher', t: 1.5, i: { phosphate_rock: 1 }, o: { crushed_phos: 1 } },
  { id: 'phosphorus', n: 'White Phosphorus', b: 'arc', t: 4, i: { crushed_phos: 2, sand: 1, coke: 1 }, o: { phosphorus: 1, slag: 2 }, fo: { co: 20, sif4: 10 }, eq: '2Ca₃(PO₄)₂ + 6SiO₂ + 10C → P₄ + 6CaSiO₃ + 10CO', note: 'The Readman electric furnace process, 1888. At 1500°C silica drives the phosphorus out as vapour, which is condensed under water. The fluorine in the apatite leaves as SiF₄ fume.' },
  { id: 'defluor', n: 'Fluoride Scrubbing', b: 'scrubber', t: 3, fi: { sif4: 20, water: 10 }, fo: { h2sif6: 15 }, ch: { sand: 0.3 }, eq: '3SiF₄ + 2H₂O → 2H₂SiF₆ + SiO₂', note: 'Water spray turns the fume into acid and gelatinous silica. Phosphate works that skipped this killed cattle and orchards downwind with fluorosis.' },
  { id: 'neut_fluor', n: 'Fluorspar from Fluorosilicic Acid', b: 'leach', t: 3, i: { crushed_lime: 3 }, fi: { h2sif6: 20 }, o: { fluorspar: 2 }, ch: { sand: 0.3 }, fo: { co2: 10 }, bleed: ['co2'], eq: 'H₂SiF₆ + 3CaCO₃ → 3CaF₂ + SiO₂ + 3CO₂ + H₂O', note: 'Limestone locks the fluorine up as insoluble calcium fluoride.' },
  { id: 'hf', n: 'Hydrofluoric Acid', b: 'retort', t: 3, i: { fluorspar: 1 }, fi: { acid: 10 }, o: { gypsum: 1 }, fo: { hf: 10 }, eq: 'CaF₂ + H₂SO₄ → 2HF + CaSO₄', note: 'Fluorspar roasted with strong sulfuric acid in a rotating kiln. Run it in lead-lined pipe: it dissolves glass and titanium.' },
  { id: 'cryolite', n: 'Synthetic Cryolite', b: 'leach', t: 3, i: { al_hydroxide: 1 }, fi: { hf: 20, naoh: 10 }, o: { cryolite: 1 }, eq: 'Al(OH)₃ + 6HF + 3NaOH → Na₃AlF₆ + 6H₂O', note: 'Natural cryolite came from a single mine at Ivigtut in Greenland, worked out by 1987. Every smelter since runs on synthetic bath.' },
  { id: 'aluminium_bath', n: 'Aluminium (fresh bath)', b: 'pot', t: 6, i: { alumina: 4, anode: 2, cryolite: 1 }, o: { aluminium: 5 }, fo: { co2: 20 }, eq: '2Al₂O₃ + 3C → 4Al + 3CO₂ (Na₃AlF₆)', note: 'Pots lose fluoride to fume and to the lining. Topping the bath up keeps it near 950°C and raises the current efficiency.' },
  { id: 'v_blow', n: 'Vanadium Blow', b: 'converter', t: 5, i: { v_pig: 3 }, o: { steel: 2, v_slag: 1 }, fo: { co2: 15 }, eq: '4V + 3O₂ → 2V₂O₃ ; C + O₂ → CO₂', note: 'Vanadium burns before carbon, so a short first blow skims it off as slag. A second blow finishes the steel.' },
  { id: 'salt_roast', n: 'Salt Roast', b: 'roaster', t: 4, i: { v_slag: 2, soda_ash: 1 }, o: { na_vanadate: 1, slag: 1 }, fo: { co2: 10 }, eq: 'V₂O₃ + O₂ + Na₂CO₃ → 2NaVO₃ + CO₂', note: 'Roasting with soda at 850°C turns insoluble vanadium oxide into soluble sodium vanadate.' },
  { id: 'amv', n: 'Ammonium Metavanadate', b: 'leach', t: 3, i: { na_vanadate: 1 }, fi: { water: 10, nh4cl: 10 }, o: { amv: 1 }, fo: { brine: 10 }, bleed: ['brine'], eq: 'NaVO₃ + NH₄Cl → NH₄VO₃↓ + NaCl', note: 'Uses the ammonium chloride liquor from the Solvay tower. The salt water left over can feed brine users.' },
  { id: 'v2o5', n: 'Vanadium Pentoxide', b: 'kiln', t: 3, i: { amv: 2 }, o: { v2o5: 1 }, fo: { nh3: 10 }, eq: '2NH₄VO₃ → V₂O₅ + 2NH₃ + H₂O', note: 'Calcining drives the ammonia back off. Pipe it away or it vents.' },
  { id: 'v_cat', n: 'V₂O₅ Catalyst Rings', b: 'workshop', t: 4, i: { v2o5: 1, sand: 2 }, o: { v_cat: 2 }, note: 'Real rings use diatomite and potassium sulfate as a promoter. At 420-600°C the salt melts and the vanadium works in a liquid film inside the pores.' },
  { id: 'cat_recycle', n: 'Catalyst Recycling', b: 'leach', t: 3, i: { spent_v_cat: 2 }, fi: { naoh: 10 }, o: { na_vanadate: 1, sand: 2 }, eq: 'V₂O₅ + 2NaOH → 2NaVO₃ + H₂O', note: 'Caustic leaches the vanadium out of spent rings. Most of the world\'s spent catalyst goes back this way.' },
  { id: 'fe_cat', n: 'Fused Iron Catalyst', b: 'arc', t: 4, i: { iron_conc: 3, alumina: 1, crushed_lime: 1 }, o: { fe_cat: 2 }, eq: 'Fe₃O₄ + Al₂O₃ + CaO, melted at 1600°C', note: 'Alumina stops the iron crystals sintering together; lime and potash speed the reaction. The magnetite is reduced to porous α-iron by the gas once it is in the converter.' },
  { id: 'v_steel', n: 'Vanadium Steel', b: 'converter', t: 4, i: { steel: 4, v2o5: 1, aluminium: 1 }, o: { v_steel: 4, slag: 1 }, eq: '3V₂O₅ + 10Al → 6V + 5Al₂O₃', note: 'Aluminium strips the oxygen from V₂O₅ in a fierce thermite reaction, and the vanadium dissolves into the steel.' },
  { id: 'crude', n: 'Crude Oil', b: 'pumpjack', t: 1, well: 1, fo: { crude: 10 }, note: 'Edwin Drake drilled the first commercial oil well in Pennsylvania in 1859, 21 m deep. The well draws down the reservoir under it.' },
  { id: 'distil', n: 'Atmospheric Distillation', b: 'cdu', t: 4, fi: { crude: 40, steam: 10 }, fo: { fuel_gas: 8, naphtha: 12, gas_oil: 12 }, o: { bitumen: 1 }, bleed: ['fuel_gas'], eq: 'Crude → gas + naphtha + gas oil + residue', note: 'Every cut is a mixture, split only by boiling range. Stripping steam lowers the partial pressure so heavy oil boils off without cracking.' },
  { id: 'steam_crack', n: 'Steam Cracking', b: 'cracker', t: 3, fi: { naphtha: 20, steam: 10, fuel_gas: 4 }, fo: { ethylene: 12, fuel_gas: 8 }, ch: { pet_coke: 0.1 }, bleed: ['fuel_gas'], eq: 'C₆H₁₄ → 2C₂H₄ + C₂H₆ (850°C, 0.3 s)', note: 'Steam dilutes the hydrocarbon so the chains break into small olefins instead of carbon. The gas is quenched in milliseconds. Coke still builds up in the tubes and has to be burned out.' },
  { id: 'smr', n: 'Steam Reforming', b: 'cracker', t: 3, fi: { fuel_gas: 20, steam: 20 }, fo: { h2: 40, co2: 10 }, bleed: ['co2'], eq: 'CH₄ + 2H₂O → CO₂ + 4H₂ (nickel catalyst)', note: 'Methane and steam over nickel at 850°C, then a shift reactor turns the CO to more hydrogen. Today most ammonia plants are fed this way instead of from coke.' },
  { id: 'edc_crack', n: 'EDC Cracking', b: 'cracker', t: 3, fi: { edc: 20, fuel_gas: 4 }, fo: { vcm: 20, hcl: 20 }, eq: 'C₂H₄Cl₂ → C₂H₃Cl + HCl (500°C)', note: 'Every tonne of vinyl chloride gives off HCl. Send it to the chlorinator so none is wasted.' },
  { id: 'edc', n: 'EDC (direct chlorination)', b: 'reactor', t: 3, fi: { ethylene: 20, cl2: 20 }, fo: { edc: 20 }, eq: 'C₂H₄ + Cl₂ → C₂H₄Cl₂ (FeCl₃)', note: 'Chlorine adds straight across the double bond in liquid EDC with a little ferric chloride.' },
  { id: 'oxychlor', n: 'EDC (oxychlorination)', b: 'chlorinator', t: 3, fi: { ethylene: 10, hcl: 20 }, fo: { edc: 10 }, eq: '2C₂H₄ + 4HCl + O₂ → 2C₂H₄Cl₂ + 2H₂O (CuCl₂)', note: 'A fluidised bed of copper chloride on alumina recycles the HCl from the cracker with air. Direct chlorination plus oxychlorination is the balanced process: chlorine and ethylene in, only PVC and water out.' },
  { id: 'polyethylene', b: 'reactor', t: 3, fi: { ethylene: 30 }, o: { polyethylene: 2 }, eq: 'n C₂H₄ → (C₂H₄)ₙ', note: 'Ziegler-Natta titanium catalysts made it at low pressure from 1953, giving dense, stiff HDPE.' },
  { id: 'pvc', b: 'reactor', t: 3, fi: { vcm: 30, water: 20 }, o: { pvc: 2 }, eq: 'n C₂H₃Cl → (C₂H₃Cl)ₙ', note: 'Suspension polymerisation: droplets of liquid vinyl chloride stirred in water each polymerise into a grain of resin.' },
  { id: 'pet_coke', n: 'Petroleum Coke', b: 'coke_oven', t: 4, i: { bitumen: 2 }, o: { pet_coke: 1 }, fo: { fuel_gas: 10 }, bleed: ['fuel_gas'], note: 'A delayed coker holds hot residue in a drum until it cracks to gas, naphtha and solid coke, which is cut out with water jets.' },
  { id: 'anode_pet', n: 'Carbon Anode (pet coke)', b: 'coke_oven', t: 4, i: { pet_coke: 2, pitch: 1 }, o: { anode: 3 }, note: 'Calcined petroleum coke bound with coal tar pitch is what real smelters use: it is low in ash and metals that would spoil the aluminium.' },
  { id: 'steam_fuelgas', n: 'Steam (fuel gas)', b: 'boiler', t: 2, fi: { fuel_gas: 20, water: 60 }, fo: { steam: 60 }, eq: 'CH₄ + 2O₂ → CO₂ + 2H₂O' },
  { id: 'steam_oil', n: 'Steam (gas oil)', b: 'boiler', t: 3, fi: { gas_oil: 10, water: 90 }, fo: { steam: 90 }, eq: '2C₁₆H₃₄ + 49O₂ → 32CO₂ + 34H₂O', note: 'Oil firing replaced coal in ships and power stations from the 1910s: no stokers, no ash.' },
  { id: 'crush_sylv', b: 'crusher', t: 1, i: { sylvinite: 1 }, o: { crushed_sylv: 1 } },
  { id: 'potash', b: 'flotation', t: 3, i: { crushed_sylv: 2 }, fi: { brine: 10 }, o: { potash: 1, salt: 1 }, eq: 'KCl floats on amine collector; NaCl sinks', note: 'The cell runs in saturated brine, not water, or the salts would just dissolve. Amine collectors coat only the sylvite crystals.' },
  { id: 'wet_phos', n: 'Phosphoric Acid', b: 'leach', t: 4, i: { crushed_phos: 2 }, fi: { acid: 30, water: 10 }, fo: { h3po4: 20, sif4: 4 }, o: { gypsum: 2 }, bleed: ['sif4'], eq: 'Ca₅(PO₄)₃F + 5H₂SO₄ → 3H₃PO₄ + 5CaSO₄ + HF', note: 'Wet process. Every tonne of P₂O₅ leaves about five tonnes of phosphogypsum, and the fluoride comes off as SiF₄ that should go to a scrubber.' },
  { id: 'ssp', n: 'Single Superphosphate', b: 'granulator', t: 3, i: { crushed_phos: 2 }, fi: { acid: 20 }, o: { ssp: 3 }, fo: { sif4: 2 }, bleed: ['sif4'], eq: 'Ca₅(PO₄)₃F + 3.5H₂SO₄ → 1.5Ca(H₂PO₄)₂ + 3.5CaSO₄ + HF', note: 'Acid turns insoluble rock phosphate into a salt that dissolves in soil water so roots can take it up.' },
  { id: 'tsp', n: 'Triple Superphosphate', b: 'granulator', t: 3, i: { crushed_phos: 1 }, fi: { h3po4: 20 }, o: { tsp: 2 }, eq: 'Ca₅(PO₄)₃F + 7H₃PO₄ → 5Ca(H₂PO₄)₂ + HF' },
  { id: 'dap', n: 'Diammonium Phosphate', b: 'granulator', t: 3, fi: { nh3: 20, h3po4: 20 }, o: { dap: 2 }, eq: '2NH₃ + H₃PO₄ → (NH₄)₂HPO₄', note: 'Ammonia is sparged into the rolling bed through a pipe below the surface; the heat of neutralisation dries the granules.' },
  { id: 'urea', b: 'reactor', t: 3, fi: { nh3: 20, co2: 10 }, o: { urea: 2 }, eq: '2NH₃ + CO₂ → NH₂COONH₄ → CO(NH₂)₂ + H₂O', note: 'Bosch-Meiser process, 1922: about 150 bar and 190°C. The CO₂ usually comes from the same plant\'s steam reformer.' },
  { id: 'npk', n: 'NPK Compound', b: 'granulator', t: 3, i: { dap: 1, potash: 1, urea: 1 }, o: { npk: 3 } },
  { id: 'hydrotreat', n: 'Hydrotreating', b: 'reactor', t: 3, fi: { gas_oil: 20, h2: 6 }, fo: { diesel: 18, h2s: 4 }, bleed: ['h2s'], eq: 'R-SH + H₂ → R-H + H₂S (CoMo catalyst, 350°C)', note: 'Hydrogen strips sulfur out of the oil as H₂S. Vented H₂S is toxic and stinks, so send it to a Claus unit.' },
  { id: 'claus', n: 'Claus Sulfur', b: 'claus', t: 2, fi: { h2s: 20, water: 15 }, o: { sulfur: 2 }, fo: { steam: 15, so2: 1 }, bleed: ['so2'], eq: 'H₂S + 1.5O₂ → SO₂ + H₂O ; 2H₂S + SO₂ → 3S + 2H₂O', note: 'Carl Friedrich Claus, 1883. A third of the H₂S burns to SO₂, which then reacts with the rest over alumina. About 97% of the sulfur comes out; the tail gas carries the rest.' },
  { id: 'burn_sulfur', n: 'Sulfur Burning', b: 'roaster', t: 2, i: { sulfur: 1 }, fo: { so2: 30 }, eq: 'S + O₂ → SO₂', note: 'Most acid plants today burn molten sulfur recovered from oil and gas, not ore. The gas is clean and strong.' },
  { id: 'soften', n: 'Lime Softening', b: 'leach', t: 2, i: { quicklime: 1 }, fi: { water: 120 }, fo: { bfw: 120 }, o: { crushed_lime: 2 }, eq: 'Ca(HCO₃)₂ + Ca(OH)₂ → 2CaCO₃↓ + 2H₂O', note: 'Thomas Clark\'s process, 1841. Slaked lime turns dissolved calcium bicarbonate into chalk that settles out, so it never bakes onto boiler tubes.' },
  { id: 'diesel_power', n: 'Power (diesel)', b: 'diesel_gen', t: 2, fi: { diesel: 10 }, fo: { co2: 6 }, bleed: ['co2'], eq: 'C₁₂H₂₆ + 18.5O₂ → 12CO₂ + 13H₂O' },
  { id: 'gasoil_power', n: 'Power (raw gas oil)', b: 'diesel_gen', t: 2, fi: { gas_oil: 10 }, fo: { co2: 6, so2: 3 }, bleed: ['co2', 'so2'], eq: 'Fuel S + O₂ → SO₂', note: 'Untreated gas oil holds about 1% sulfur, which leaves the exhaust as SO₂ and brings acid rain.' },
  { id: 'wp_shell', n: 'WP Shell', b: 'workshop', t: 3, lock: 1, i: { plate: 1, brass: 1, phosphorus: 1, black_powder: 1 }, o: { wp_shell: 2 }, note: 'The phosphorus is poured in molten under water and sealed before it can touch air.' },
  { id: 'cartridge', b: 'workshop', t: 2, i: { brass: 1, lead: 1, black_powder: 1 }, o: { cartridge: 2 } },
];

const RECIPE = {};
for (const r of RECIPES) {
  RECIPE[r.id] = r;
  const first = Object.keys(r.o || r.fo)[0];
  r.n = r.n || (ITEMS[first] || FLUIDS[first]).n;
}

const START_INV = {
  belt: 80, pipe: 40, steel_pipe: 10, lead_pipe: 10, booster: 1, chest: 8, sorter: 4, miner: 8, pump: 1, boiler: 2, engine: 2,
  crusher: 3, mill: 2, magsep: 1, flotation: 2, coke_oven: 2, kiln: 1, blast: 1, converter: 1, workshop: 2,
  casting: 20, brick: 10, stack: 1, turret: 2, cartridge: 40, brick_wall: 20, projector: 1, filler: 1,
};

const ORDERS = [
  { c: 'Farmers\' cooperative', item: 'ssp', n: 60, tier: 1, rw: { motor: 4, plate: 20 }, d: 'Superphosphate for the spring sowing.' },
  { c: 'Town gasworks', item: 'coke', n: 100, tier: 1, rw: { brick: 40, casting: 20 }, d: 'Coke for the retort house and the gas holders.' },
  { c: 'Railway company', item: 'steel', n: 80, tier: 1, rw: { miner: 2, belt: 60 }, d: 'Steel for rails and boiler plate.' },
  { c: 'Builders\' merchant', item: 'cement', n: 60, tier: 1, rw: { casting: 40, chest: 4 }, d: 'Portland cement for the new bridge.' },
  { c: 'Electrical contractor', item: 'wire', n: 120, tier: 1, rw: { motor: 4, steel_pipe: 10 }, d: 'Copper wire for the tramway.' },
  { c: 'Paper mill', item: 'quicklime', n: 60, tier: 1, rw: { plate: 30 }, d: 'Lime to recausticise their pulping liquor.' },
  { c: 'Water board', item: 'bleach', n: 40, tier: 2, rw: { glass_pipe: 10, booster: 2 }, d: 'Bleaching powder to chlorinate the town water. Typhoid deaths fell by 90% wherever it was used.' },
  { c: 'Glassworks', item: 'soda_ash', n: 60, tier: 2, rw: { workshop: 1, motor: 4 }, d: 'Soda ash for bottle glass.' },
  { c: 'Quarry', item: 'black_powder', n: 60, tier: 2, rw: { crusher: 2, mill: 1 }, d: 'Blasting powder for the face.' },
  { c: 'Market gardens', item: 'amm_sulfate', n: 50, tier: 2, rw: { leach: 1, lead_pipe: 10 }, d: 'Sulfate of ammonia for the glasshouses.' },
  { c: 'Aircraft works', item: 'aluminium', n: 60, tier: 2, rw: { wire: 60, motor: 6 }, d: 'Aluminium sheet for airframes.' },
  { c: 'Photographic works', item: 'silver', n: 10, tier: 2, rw: { glass: 20, plate: 30 }, d: 'Silver for silver nitrate plates.' },
  { c: 'Grain belt farms', item: 'dap', n: 80, tier: 3, rw: { granulator: 1, motor: 6 }, d: 'DAP for the wheat belt.' },
  { c: 'Rice growers', item: 'urea', n: 80, tier: 3, rw: { reactor: 1, steel_pipe: 20 }, d: 'Urea for the paddies. It is the cheapest nitrogen to ship.' },
  { c: 'Fruit orchards', item: 'potash', n: 60, tier: 3, rw: { flotation: 1, belt: 60 }, d: 'Potash for the apple orchards. Fruit draws potassium out of the soil fast.' },
  { c: 'Agricultural merchant', item: 'npk', n: 90, tier: 3, rw: { v_cat: 4, fe_cat: 4 }, d: 'Compound NPK for small farms.' },
  { c: 'Sugar estate', item: 'tsp', n: 60, tier: 3, rw: { ti_pipe: 10 }, d: 'Triple superphosphate for the cane fields.' },
  { c: 'Cable maker', item: 'pvc', n: 50, tier: 3, rw: { pvc_pipe: 20, motor: 4 }, d: 'PVC for cable sheathing.' },
  { c: 'Packaging firm', item: 'polyethylene', n: 50, tier: 3, rw: { pe_pipe: 20, wire: 40 }, d: 'Polyethylene for film and bottles.' },
  { c: 'Shipyard', item: 'v_steel', n: 40, tier: 3, rw: { armour_wall: 10, steel: 40 }, d: 'Vanadium steel for propeller shafts.' },
  { c: 'Chemical plant', item: 'titanium', n: 30, tier: 3, rw: { ti_pipe: 20 }, d: 'Titanium for heat exchangers handling wet chlorine.' },
];

const CATS = ['Logistics', 'Mining', 'Power', 'Processing', 'Smelting', 'Chemistry', 'Defence'];
